"""HTML-Backtest-Report-Generator (matplotlib + jinja-free).

Bewusst zero-dependency-only: HTML wird mit f-strings gebaut, Plots als
Base64-eingebettete PNGs. Kein Jinja-Pflicht.
"""

from __future__ import annotations

import base64
import io
import logging
from pathlib import Path
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)


def _figure_to_base64() -> str:
    """Convert current matplotlib figure to base64-PNG."""
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError as e:
        raise RuntimeError("matplotlib required") from e
    buf = io.BytesIO()
    plt.savefig(buf, format="png", bbox_inches="tight", dpi=100)
    plt.close()
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("ascii")


def plot_equity_curves(
    equity_dict: dict[str, pd.Series], title: str = "Equity Curves"
) -> str:
    """Generate equity-curve plot, return base64-PNG."""
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError as e:
        raise RuntimeError("matplotlib required") from e

    plt.figure(figsize=(11, 5))
    for name, eq in equity_dict.items():
        plt.plot(eq.index, eq.values, label=name, linewidth=1.5)
    plt.title(title)
    plt.xlabel("Date")
    plt.ylabel("Cumulative Return")
    plt.legend(loc="best", fontsize=9)
    plt.grid(alpha=0.3)
    return _figure_to_base64()


def plot_drawdown(equity: pd.Series, title: str = "Drawdown") -> str:
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError as e:
        raise RuntimeError("matplotlib required") from e

    eq = pd.Series(equity)
    cummax = eq.cummax()
    dd = (eq / cummax - 1) * 100
    plt.figure(figsize=(11, 3.5))
    plt.fill_between(dd.index, dd.values, 0, color="red", alpha=0.4)
    plt.plot(dd.index, dd.values, color="darkred", linewidth=1)
    plt.title(title)
    plt.ylabel("Drawdown (%)")
    plt.grid(alpha=0.3)
    return _figure_to_base64()


def plot_rolling_sharpe(returns: pd.Series, window: int = 63) -> str:
    """Rolling 3-month Sharpe-Ratio."""
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError as e:
        raise RuntimeError("matplotlib required") from e
    import numpy as np

    r = pd.Series(returns).dropna()
    rs = r.rolling(window).mean() / r.rolling(window).std() * np.sqrt(252)
    plt.figure(figsize=(11, 3.5))
    plt.plot(rs.index, rs.values, linewidth=1.2)
    plt.axhline(0, color="black", linestyle="--", alpha=0.5)
    plt.title(f"Rolling Sharpe (window={window} days)")
    plt.ylabel("Sharpe Ratio")
    plt.grid(alpha=0.3)
    return _figure_to_base64()


def plot_returns_distribution(returns: pd.Series) -> str:
    try:
        import matplotlib.pyplot as plt  # type: ignore
    except ImportError as e:
        raise RuntimeError("matplotlib required") from e

    r = pd.Series(returns).dropna()
    plt.figure(figsize=(8, 4))
    plt.hist(r, bins=80, alpha=0.7, edgecolor="black")
    plt.axvline(r.mean(), color="red", linestyle="--", label=f"Mean={r.mean():.4f}")
    plt.axvline(
        r.median(), color="green", linestyle="--", label=f"Median={r.median():.4f}"
    )
    plt.title("Returns Distribution")
    plt.xlabel("Daily Return")
    plt.ylabel("Frequency")
    plt.legend()
    plt.grid(alpha=0.3)
    return _figure_to_base64()


_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>{title}</title>
<style>
body {{ font-family: Helvetica, Arial, sans-serif; margin: 24px; max-width: 1200px; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: 8px; }}
h2 {{ margin-top: 32px; color: #555; }}
table {{ border-collapse: collapse; margin: 16px 0; }}
th, td {{ border: 1px solid #ddd; padding: 6px 12px; text-align: right; }}
th {{ background: #f4f4f4; }}
td.label {{ text-align: left; font-weight: 600; }}
img {{ max-width: 100%; margin: 12px 0; }}
.section {{ margin-bottom: 32px; }}
.footnote {{ color: #888; font-size: 0.9em; margin-top: 24px; }}
</style></head><body>
<h1>{title}</h1>
<p class="footnote">Generated: {date}</p>
{sections}
<p class="footnote">Generated by erweiterung.report.html_report.  Synthesized analytics, not investment advice.</p>
</body></html>"""


def metrics_table_html(metrics: dict) -> str:
    rows = []
    for k, v in metrics.items():
        if isinstance(v, (int, float)):
            try:
                rows.append(
                    f'<tr><td class="label">{k}</td><td>{float(v):+.4f}</td></tr>'
                )
            except (TypeError, ValueError):
                rows.append(f'<tr><td class="label">{k}</td><td>{v}</td></tr>')
        else:
            rows.append(f'<tr><td class="label">{k}</td><td>{v}</td></tr>')
    return "<table>" + "".join(rows) + "</table>"


def _try_plot(fn, *args, **kwargs):
    """Run a plotting function; return base64-png or None if matplotlib unavailable."""
    try:
        return fn(*args, **kwargs)
    except (RuntimeError, ImportError) as e:
        if "matplotlib" in str(e).lower():
            logger.info("matplotlib unavailable - skipping plot %s", fn.__name__)
            return None
        raise


def _ascii_equity_summary(equity_dict: dict[str, pd.Series]) -> str:
    rows = [
        "<table><tr><th>Strategy</th><th>Final Equity</th><th>Best Day</th><th>Worst Day</th></tr>"
    ]
    for name, eq in equity_dict.items():
        ret = eq.pct_change().dropna()
        if ret.empty:
            continue
        rows.append(
            f"<tr><td class='label'>{name}</td>"
            f"<td>{float(eq.iloc[-1]):.4f}</td>"
            f"<td>{float(ret.max()):+.4f}</td>"
            f"<td>{float(ret.min()):+.4f}</td></tr>"
        )
    rows.append("</table>")
    return "".join(rows)


def generate_full_report(
    title: str,
    strategy_returns: dict[str, pd.Series],
    metrics: dict[str, dict],
    output_path: str,
    main_strategy: Optional[str] = None,
) -> str:
    """Build full HTML backtest report.

    Falls matplotlib nicht verfügbar ist, werden Plots durch Tabellen ersetzt
    — der Report bleibt voll lesbar.
    """
    if not strategy_returns:
        raise ValueError("no strategies given")
    main = main_strategy or next(iter(strategy_returns))

    sections = []
    eq_dict = {k: (1 + v).cumprod() for k, v in strategy_returns.items()}

    eq_b64 = _try_plot(plot_equity_curves, eq_dict)
    if eq_b64:
        sections.append(
            f'<div class="section"><h2>Equity Curves</h2><img src="data:image/png;base64,{eq_b64}"/></div>'
        )
    else:
        sections.append(
            f'<div class="section"><h2>Equity Curves (matplotlib unavailable - text only)</h2>{_ascii_equity_summary(eq_dict)}</div>'
        )

    dd_b64 = _try_plot(plot_drawdown, eq_dict[main])
    if dd_b64:
        sections.append(
            f'<div class="section"><h2>Drawdown ({main})</h2><img src="data:image/png;base64,{dd_b64}"/></div>'
        )

    rs_b64 = _try_plot(plot_rolling_sharpe, strategy_returns[main])
    if rs_b64:
        sections.append(
            f'<div class="section"><h2>Rolling Sharpe ({main})</h2><img src="data:image/png;base64,{rs_b64}"/></div>'
        )

    rd_b64 = _try_plot(plot_returns_distribution, strategy_returns[main])
    if rd_b64:
        sections.append(
            f'<div class="section"><h2>Returns Distribution ({main})</h2><img src="data:image/png;base64,{rd_b64}"/></div>'
        )

    metrics_html = "<div class='section'><h2>Performance Metrics</h2>"
    for name, m in metrics.items():
        metrics_html += f"<h3>{name}</h3>" + metrics_table_html(m)
    metrics_html += "</div>"
    sections.append(metrics_html)

    html = _TEMPLATE.format(
        title=title,
        date=pd.Timestamp.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        sections="\n".join(sections),
    )
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(html, encoding="utf-8")
    return str(p.resolve())


__all__ = [
    "plot_equity_curves",
    "plot_drawdown",
    "plot_rolling_sharpe",
    "plot_returns_distribution",
    "metrics_table_html",
    "generate_full_report",
]
