"""STRATEGY-V2: 30-factor multi-factor strategy with regime-conditional weights.

Active factors (30):
  - Trend (1-4): EMA spread, MA200 position, ADX strength, MACD histogram
  - Momentum (5-7): RSI centered, volume-weighted momentum, OBV trend
  - Mean-reversion (8-9, 16-17): Bollinger %B, Stochastic, 3d reversal, RSI extreme
  - Volume (10-11): abnormal volume, tick imbalance
  - Volatility (12-13): regime score, VoV penalty
  - Breadth (14-15): pct above MA, advance-decline slope
  - Sector (18): rotation bias
  - Earnings/Insider (19-20): EPS surprise z, insider activity score
  - News/Macro (21-24): sentiment, volume spike, growth momentum, inflation
  - Intermarket (25-27): bond-equity divergence, credit spread, yield curve
  - Options (28-29): put-call extreme, VIX regime score
  - Congress (30): congressional trading activity

Crash probability is applied as a multiplicative scaler on the composite score,
not as a z-scored additive factor.

All 30 factors are now wired to their data sources. Factors gracefully degrade
to 0.0 when external data is unavailable (no dilution — zero-variance factors
are excluded from the composite via the dead-factor filter).

Factor 31 (meta-model confidence) is a multiplicative filter, not an additive
summand. It gates signals via a min-confidence threshold and scales scores.

Regime-conditional weights are loaded from configs/factor_weights_by_regime.json
(generated by scripts/train_regime_weights.py). If unavailable, default v2
weights from the factor contract are used.

Exit management: ATR-regime adaptive stops (stop-loss, trailing, take-profit)
with momentum verification for whipsaw protection.

Selection: strategy.name = "multifactor_v2" in configs/app.yaml.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any

import numpy as np
import pandas as pd

from src.assembled_core.strategies.multifactor_v1 import (
    _abnormal_volume_score,
    _bollinger_score,
    _compute_breadth_score,
    _compute_ema_spread,
    _crash_prediction_multiplier,
    _empty_signals,
    _ma_position,
    _obv_trend,
    _rsi_score,
    _safe_col,
    _stochastic_score,
    _volatility_regime_score,
    _vov_penalty,
)
from src.assembled_core.strategies.multifactor_v1 import (
    REGIME_EXPOSURE,
    compute_target_positions as _v1_compute_target_positions,
)

logger = logging.getLogger(__name__)

STRATEGY_VERSION = "v2"
VERSION = "multifactor_v2.3.0"

# ---------------------------------------------------------------------------
# Default v2 factor weights (used when regime weights file is unavailable)
# ---------------------------------------------------------------------------

DEFAULT_V2_WEIGHTS: dict[str, float] = {
    # --- v1 factors (re-calibrated) ---
    "trend_ema_spread": 0.10,
    "trend_ma200_position": 0.07,
    "trend_adx_strength": 0.05,
    "trend_macd_hist": 0.05,
    "mom_rsi_centered": 0.06,
    "mom_volume_weighted": 0.05,
    "mom_obv_trend": 0.03,
    "mr_bollinger_pctb": 0.04,
    "mr_stoch_oversold": 0.03,
    "vol_abnormal": 0.03,
    "vol_tick_imbalance": 0.03,
    "vola_regime_score": 0.03,
    "vola_vov_penalty": 0.03,
    "breadth_above_ma": 0.04,
    "breadth_ad_line": 0.03,
    # --- v2 factors (16-18) ---
    "mr_zscore_reversal_3d": 0.03,
    "mr_rsi_extreme_uptrend": 0.03,
    "sector_rotation_bias": 0.04,
    # --- Earnings/Insider (19-20) ---
    "earnings_surprise_z": 0.03,
    "insider_activity_score": 0.02,
    # --- News/Macro (21-24) ---
    "news_sentiment_7d": 0.02,
    "news_volume_spike": 0.01,
    "macro_growth_momentum": 0.02,
    "macro_inflation_surprise": 0.01,
    # --- Intermarket (25-27) ---
    "intermarket_bond_equity": 0.02,
    "intermarket_credit_spread": 0.02,
    "intermarket_yield_curve": 0.02,
    # --- Options (28-29) ---
    "options_put_call_extreme": 0.02,
    "vix_regime_score": 0.02,
    # --- Congress (30) ---
    "congress_activity": 0.02,
    # NOTE: crash_probability_inverse is applied as a multiplicative scaler
    # on the final composite, not as an additive factor.
    # Sum = 1.00
}

# ---------------------------------------------------------------------------
# Regime weights cache
# ---------------------------------------------------------------------------

_REGIME_WEIGHTS_CACHE: dict[str, dict[str, float]] | None = None


def _load_regime_weights(cfg: dict[str, Any]) -> dict[str, dict[str, float]] | None:
    """Load regime-conditional factor weights from JSON file.

    Returns None if the file is missing or unparseable (defensive).
    """
    global _REGIME_WEIGHTS_CACHE  # noqa: PLW0603
    if _REGIME_WEIGHTS_CACHE is not None:
        return _REGIME_WEIGHTS_CACHE

    path = cfg.get("regime_weights_path", "configs/factor_weights_by_regime.json")
    if not os.path.isfile(path):
        logger.debug("[MF-V2] Regime weights file not found: %s", path)
        return None
    try:
        with open(path) as fh:
            data = json.load(fh)
        # Validate: must have at least one regime key with a dict value
        regimes = {k: v for k, v in data.items() if isinstance(v, dict) and not k.startswith("_")}
        if not regimes:
            return None
        _REGIME_WEIGHTS_CACHE = regimes
        logger.info("[MF-V2] Loaded regime weights for regimes: %s", list(regimes.keys()))
        return regimes
    except Exception as exc:
        logger.debug("[MF-V2] Failed to load regime weights: %s", exc)
        return None


def _get_weights_for_regime(
    regime_label: str,
    cfg: dict[str, Any],
) -> dict[str, float]:
    """Return factor weights for the given regime, or defaults."""
    regime_weights = _load_regime_weights(cfg)
    if regime_weights and regime_label in regime_weights:
        return regime_weights[regime_label]
    return DEFAULT_V2_WEIGHTS


# ---------------------------------------------------------------------------
# Regime detection (reuses v1 logic)
# ---------------------------------------------------------------------------


def _detect_regime(df: pd.DataFrame, cfg: dict[str, Any]) -> str:
    """Detect current market regime label."""
    try:
        from src.assembled_core.risk.regime_models import build_regime_state

        regime_df = build_regime_state(df)
        if regime_df is not None and not regime_df.empty:
            label = str(regime_df.iloc[-1].get("regime_label", "neutral")).lower()
            return label
    except Exception:
        pass

    # Fallback: breadth-based
    breadth = _compute_breadth_score(df)
    if breadth < -0.4:
        return "bear"
    if breadth < -0.1:
        return "sideways"
    if breadth > 0.3:
        return "bull"
    return "sideways"


# ---------------------------------------------------------------------------
# New factor computations (factors 16-29)
# ---------------------------------------------------------------------------


def _compute_breadth_ad_slope(df: pd.DataFrame) -> float:
    """Factor 15: Advance-decline ratio slope (5-day).

    Counts symbols where close > close_5d_ago (advances) vs
    close < close_5d_ago (declines). Returns AD ratio centered
    around 0: ratio = advances / (advances + declines), score = (ratio - 0.5) * 2.
    This is genuinely different from breadth_above_ma (pct above MA50).
    """
    if df.empty or "symbol" not in df.columns or "close" not in df.columns:
        return 0.0
    try:
        sorted_df = df.sort_values("timestamp")
        latest = sorted_df.groupby("symbol", group_keys=False).tail(1)
        hist_5d = sorted_df.groupby("symbol", group_keys=False).nth(-6)

        if latest.empty or hist_5d.empty:
            return 0.0

        latest_prices = latest.set_index("symbol")["close"].astype(float)
        hist_prices = hist_5d.set_index("symbol")["close"].astype(float)
        common = latest_prices.index.intersection(hist_prices.index)
        if len(common) < 2:
            return 0.0

        advances = (latest_prices[common] > hist_prices[common]).sum()
        declines = (latest_prices[common] < hist_prices[common]).sum()
        total = advances + declines
        if total == 0:
            return 0.0
        ratio = float(advances) / float(total)
        return (ratio - 0.5) * 2.0
    except Exception:
        return 0.0


def _compute_mr_zscore_reversal_3d(df: pd.DataFrame) -> pd.Series:
    """Factor 16: 3-day return z-score inverted (oversold = positive)."""
    try:
        from src.assembled_core.features.mean_reversion_factors import (
            compute_mean_reversion_factors,
        )
        mr_df = compute_mean_reversion_factors(df)
        if mr_df is not None and "mr_zscore_reversal_3d" in mr_df.columns:
            latest = mr_df.sort_values("timestamp").groupby("symbol", group_keys=False).tail(1)
            return latest.set_index("symbol")["mr_zscore_reversal_3d"]
    except Exception as exc:
        logger.debug("[MF-V2] mr_zscore_reversal_3d unavailable: %s", exc)
    return pd.Series(dtype=float)


def _compute_mr_rsi_extreme_uptrend(df: pd.DataFrame) -> pd.Series:
    """Factor 17: RSI < 30 in uptrend signal."""
    try:
        from src.assembled_core.features.mean_reversion_factors import (
            compute_mean_reversion_factors,
        )
        mr_df = compute_mean_reversion_factors(df)
        if mr_df is not None and "mr_rsi_extreme_uptrend" in mr_df.columns:
            latest = mr_df.sort_values("timestamp").groupby("symbol", group_keys=False).tail(1)
            return latest.set_index("symbol")["mr_rsi_extreme_uptrend"]
    except Exception as exc:
        logger.debug("[MF-V2] mr_rsi_extreme_uptrend unavailable: %s", exc)
    return pd.Series(dtype=float)


def _compute_sector_rotation_bias(
    df: pd.DataFrame,
    latest_symbols: list[str],
    cfg: dict[str, Any],
) -> pd.Series:
    """Factor 18: Sector rotation bias per symbol.

    Maps each symbol to its GICS sector via security_meta.csv, then looks up
    the sector score from the sector_rotation module. Top-3 sectors get a
    boost (1.0), bottom-2 get penalty (-1.0), rest neutral (0.0).
    """
    try:
        meta_path = cfg.get("security_meta_path", "configs/security_meta.csv")
        if not os.path.isfile(meta_path):
            return pd.Series(0.0, index=latest_symbols)

        meta = pd.read_csv(meta_path, dtype={"symbol": str, "sector": str})
        sym_to_sector = dict(zip(meta["symbol"], meta["sector"]))

        from src.assembled_core.signals.sector_rotation import (
            compute_sector_scores,
            SECTOR_ETFS,
            SECTOR_NAMES,
        )

        # Extract sector ETF prices from df if available
        sector_syms = [s for s in SECTOR_ETFS if s in df["symbol"].unique()]
        if len(sector_syms) < 3:
            return pd.Series(0.0, index=latest_symbols)

        sector_prices = df[df["symbol"].isin(sector_syms)].copy()
        spy_prices = df[df["symbol"] == "SPY"].copy()
        if spy_prices.empty:
            return pd.Series(0.0, index=latest_symbols)

        scores_df = compute_sector_scores(sector_prices, spy_prices)
        if scores_df.empty:
            return pd.Series(0.0, index=latest_symbols)

        # Get latest row scores
        latest_scores = scores_df.iloc[-1]
        etf_scores = {}
        for etf in sector_syms:
            col = f"{etf}_score"
            if col in latest_scores.index:
                etf_scores[etf] = float(latest_scores[col])

        if not etf_scores:
            return pd.Series(0.0, index=latest_symbols)

        # Rank sectors: top 3 = +1, bottom 2 = -1, rest = 0
        sorted_etfs = sorted(etf_scores, key=etf_scores.get, reverse=True)
        top_sectors = {SECTOR_NAMES.get(e, "") for e in sorted_etfs[:3]}
        bottom_sectors = {SECTOR_NAMES.get(e, "") for e in sorted_etfs[-2:]}

        result = {}
        for sym in latest_symbols:
            sector = sym_to_sector.get(sym, "")
            if sector in top_sectors:
                result[sym] = 1.0
            elif sector in bottom_sectors:
                result[sym] = -1.0
            else:
                result[sym] = 0.0

        return pd.Series(result)
    except Exception as exc:
        logger.debug("[MF-V2] sector_rotation_bias unavailable: %s", exc)
        return pd.Series(0.0, index=latest_symbols)


def _compute_earnings_insider_factors(
    latest_symbols: list[str],
    cfg: dict[str, Any],
) -> tuple[pd.Series, pd.Series]:
    """Factors 19-20: earnings surprise z, insider activity score."""
    try:
        from src.assembled_core.features.earnings_insider_wrapper import (
            compute_earnings_insider_factors,
        )
        as_of = pd.Timestamp.now().normalize()
        # Need earnings_df and filings_df from data sources
        # These are PIT-safe wrappers — pass empty frames if no data
        earnings_df = pd.DataFrame(
            columns=["symbol", "filing_date", "surprise_pct"]
        )
        filings_df = pd.DataFrame(
            columns=["symbol", "filing_date", "shares_delta"]
        )
        result = compute_earnings_insider_factors(
            as_of, latest_symbols, earnings_df, filings_df
        )
        if result is not None and not result.empty:
            earn_z = result.get("earnings_surprise_z", pd.Series(dtype=float))
            insider = result.get("insider_activity_z", pd.Series(dtype=float))
            return earn_z, insider
    except Exception as exc:
        logger.debug("[MF-V2] earnings/insider factors unavailable: %s", exc)
    empty = pd.Series(dtype=float)
    return empty, empty


def _compute_news_macro_factors(
    latest_symbols: list[str],
    cfg: dict[str, Any],
) -> dict[str, pd.Series]:
    """Factors 21-24: news sentiment, volume spike, macro growth, inflation."""
    result: dict[str, pd.Series] = {}
    try:
        from src.assembled_core.features.news_macro_wrapper import (
            compute_news_macro_factors,
        )
        as_of = pd.Timestamp.now().normalize()
        news_df = pd.DataFrame(columns=["symbol", "timestamp", "sentiment_score"])
        macro_df = pd.DataFrame(
            columns=["timestamp", "macro_code", "value", "country"]
        )
        out = compute_news_macro_factors(as_of, latest_symbols, news_df, macro_df)
        if out is not None and not out.empty:
            for col in [
                "news_sentiment_7d_z",
                "news_volume_spike_z",
                "macro_growth_momentum_z",
                "macro_inflation_surprise_z",
            ]:
                if col in out.columns:
                    result[col] = out[col]
    except Exception as exc:
        logger.debug("[MF-V2] news/macro factors unavailable: %s", exc)
    return result


def _compute_intermarket_factors(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factors 25-27: bond-equity divergence, credit spread, yield curve.

    Strategy:
    1. Read pre-merged columns from latest (populated by trading_cycle).
    2. If missing, fetch directly via build_intermarket_factors().
    Universal factors — same value per date, broadcast to all symbols.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)

    # --- Path 1: columns already in latest (from trading_cycle merge) ---
    col_map = {
        "intermarket_bond_equity": "bond_equity_divergence_flag",
        "intermarket_credit_spread": "credit_spread_change_5d",
        "intermarket_yield_curve": "yield_curve_slope",
    }
    found_any = False
    for factor_name, src_col in col_map.items():
        if src_col in latest.columns:
            vals = pd.to_numeric(latest[src_col], errors="coerce").fillna(0.0)
            result[factor_name] = pd.Series(vals.values, index=sym_idx.values)
            found_any = True

    if found_any:
        logger.debug("[MF-V2] intermarket factors: %d read from panel", len(result))
        return result

    # --- Path 2: fetch directly ---
    try:
        from src.assembled_core.features.intermarket_factors import (
            build_intermarket_factors,
        )
        im = build_intermarket_factors()
        if not im.empty:
            last_row = im.iloc[-1]
            for factor_name, src_col in col_map.items():
                val = float(last_row.get(src_col, 0.0)) if src_col in im.columns else 0.0
                result[factor_name] = pd.Series(val, index=sym_idx.values)
            logger.debug("[MF-V2] intermarket factors: fetched %d directly", len(result))
    except Exception as exc:
        logger.debug("[MF-V2] intermarket factors unavailable: %s", exc)
    return result


def _compute_options_factors(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factors 28-29: put-call extreme, VIX regime z-score.

    Fetches VIX/VIX3M/PCR from CBOESource, computes regime factors.
    Universal factors — same value per date, broadcast to all symbols.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)

    try:
        from src.assembled_core.data.sources.cboe_source import CBOESource
        from src.assembled_core.features.options_derived_signals import (
            build_options_regime_factors,
        )

        cboe = CBOESource()
        cboe_df = cboe.fetch_options_regime_data()
        if not cboe_df.empty:
            opts = build_options_regime_factors(cboe_df)
            if not opts.empty:
                last_row = opts.iloc[-1]
                pcr_extreme = float(last_row.get("equity_put_call_extreme", 0.0))
                vix_z = float(last_row.get("vix_zscore_252d", 0.0))
                result["options_put_call_extreme"] = pd.Series(pcr_extreme, index=sym_idx.values)
                result["vix_regime_score"] = pd.Series(vix_z, index=sym_idx.values)
                logger.debug(
                    "[MF-V2] options factors: pcr_extreme=%.2f, vix_z=%.2f",
                    pcr_extreme, vix_z,
                )
    except Exception as exc:
        logger.debug("[MF-V2] options factors unavailable: %s", exc)
    return result


def _compute_congress_factors(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factor 30: congressional trading activity score.

    Reads pre-merged congress columns from the panel (populated by
    trading_cycle when include_congress=True). Per-symbol factor.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)

    try:
        # Congress features are per-symbol — read from panel if available
        count_col = "congress_trade_count_90d"
        amount_col = "congress_total_amount_90d"

        if count_col in latest.columns:
            count_vals = pd.to_numeric(latest[count_col], errors="coerce").fillna(0.0)
            amount_vals = pd.to_numeric(
                latest.get(amount_col, pd.Series(0.0, index=latest.index)),
                errors="coerce",
            ).fillna(0.0)
            # Composite: normalize count + log(1+amount) as activity score
            activity = count_vals + np.log1p(amount_vals.abs()) / 10.0
            result["congress_activity"] = pd.Series(activity.values, index=sym_idx.values)
            logger.debug("[MF-V2] congress factors: %d symbols with data", (count_vals > 0).sum())
    except Exception as exc:
        logger.debug("[MF-V2] congress factors unavailable: %s", exc)
    return result


def _compute_crash_prob_inverse(df: pd.DataFrame, cfg: dict[str, Any]) -> float:
    """Factor 29: inverse crash probability (1 - crash_prob)."""
    crash_mult = _crash_prediction_multiplier(df, cfg)
    # crash_mult ranges from 0.0 (crash) to 1.0 (no crash)
    # Convert to z-score-like: 1.0 → +1, 0.0 → -3
    return (crash_mult - 0.5) * 4.0  # 1.0→+2.0, 0.5→0.0, 0.0→-2.0


# ---------------------------------------------------------------------------
# Main signal generation
# ---------------------------------------------------------------------------


def compute_signals(
    prices_with_features: pd.DataFrame,
    strategy_cfg: dict[str, Any] | None = None,
) -> pd.DataFrame:
    """Generate 30-factor signals with regime-conditional weights.

    All 30 factors are actively computed. Factors degrade gracefully to 0.0
    when external data is unavailable. Dead factors (zero variance) are
    excluded from the weighted composite to prevent dilution.

    Drop-in replacement for v1. Same input/output schema.
    """
    cfg = strategy_cfg or {}
    min_score = float(cfg.get("min_signal_score", 0.0))
    ema_fast = int(cfg.get("ema_fast", 20))
    ema_slow = int(cfg.get("ema_slow", 60))

    if prices_with_features.empty or "symbol" not in prices_with_features.columns:
        return _empty_signals()

    df = prices_with_features.copy()
    if "timestamp" not in df.columns:
        return _empty_signals()

    # Latest bar per symbol
    latest = (
        df.sort_values("timestamp")
        .groupby("symbol", group_keys=False)
        .tail(1)
        .copy()
    )
    if latest.empty:
        return _empty_signals()

    latest_symbols = latest["symbol"].tolist()

    # --- Detect regime ---
    regime_label = _detect_regime(df, cfg)
    weights = _get_weights_for_regime(regime_label, cfg)
    logger.info(
        "[MF-V2] Regime=%s, %d weight entries, universe=%d symbols",
        regime_label, len(weights), len(latest_symbols),
    )

    # --- Compute raw factor values (factors 1-15 from v1) ---
    scores = pd.DataFrame({"symbol": latest["symbol"].values})
    scores.index = latest.index

    close = pd.to_numeric(latest.get("close", pd.Series(dtype=float)), errors="coerce")

    # Factors 1-4: Trend
    scores["trend_ema_spread"] = _compute_ema_spread(df, ema_fast, ema_slow)
    scores["trend_ma200_position"] = _ma_position(latest, close, "ta_ma_200_v1", fallback_window=200)
    scores["trend_adx_strength"] = _safe_col(latest, "ta_adx_v1", default=0.0) / 100.0
    scores["trend_macd_hist"] = _safe_col(latest, "ta_macd_hist_v1", default=0.0)

    # Factors 5-7: Momentum
    scores["mom_rsi_centered"] = _rsi_score(latest)
    scores["mom_volume_weighted"] = _safe_col(latest, "ta_vol_weighted_mom_20d_v1", default=0.0)
    scores["mom_obv_trend"] = _obv_trend(df)

    # Factors 8-9: Mean-reversion guard
    scores["mr_bollinger_pctb"] = _bollinger_score(latest)
    scores["mr_stoch_oversold"] = _stochastic_score(latest)

    # Factors 10-11: Volume
    scores["vol_abnormal"] = _abnormal_volume_score(latest)
    scores["vol_tick_imbalance"] = _safe_col(latest, "tick_imbalance_20d", default=0.5)

    # Factors 12-13: Volatility
    scores["vola_regime_score"] = _volatility_regime_score(latest)
    scores["vola_vov_penalty"] = _vov_penalty(latest)

    # Factors 14-15: Breadth (two genuinely different signals)
    scores["breadth_above_ma"] = _compute_breadth_score(df)
    scores["breadth_ad_line"] = _compute_breadth_ad_slope(df)

    # --- New v2 factors (16-29) — defensive, all return NaN on failure ---

    # Factors 16-17: Mean-reversion from sidecar module
    mr_16 = _compute_mr_zscore_reversal_3d(df)
    mr_17 = _compute_mr_rsi_extreme_uptrend(df)
    scores["mr_zscore_reversal_3d"] = scores["symbol"].map(mr_16).fillna(0.0) if not mr_16.empty else 0.0
    scores["mr_rsi_extreme_uptrend"] = scores["symbol"].map(mr_17).fillna(0.0) if not mr_17.empty else 0.0

    # Factor 18: Sector rotation
    sector_bias = _compute_sector_rotation_bias(df, latest_symbols, cfg)
    scores["sector_rotation_bias"] = scores["symbol"].map(sector_bias).fillna(0.0) if not sector_bias.empty else 0.0

    # Factors 19-20: Earnings + Insider
    earn_z, insider_z = _compute_earnings_insider_factors(latest_symbols, cfg)
    scores["earnings_surprise_z"] = scores["symbol"].map(earn_z).fillna(0.0) if not earn_z.empty else 0.0
    scores["insider_activity_score"] = scores["symbol"].map(insider_z).fillna(0.0) if not insider_z.empty else 0.0

    # Factors 21-24: News + Macro
    news_macro = _compute_news_macro_factors(latest_symbols, cfg)
    scores["news_sentiment_7d"] = scores["symbol"].map(
        news_macro.get("news_sentiment_7d_z", pd.Series(dtype=float))
    ).fillna(0.0) if "news_sentiment_7d_z" in news_macro else 0.0
    scores["news_volume_spike"] = scores["symbol"].map(
        news_macro.get("news_volume_spike_z", pd.Series(dtype=float))
    ).fillna(0.0) if "news_volume_spike_z" in news_macro else 0.0
    scores["macro_growth_momentum"] = scores["symbol"].map(
        news_macro.get("macro_growth_momentum_z", pd.Series(dtype=float))
    ).fillna(0.0) if "macro_growth_momentum_z" in news_macro else 0.0
    scores["macro_inflation_surprise"] = scores["symbol"].map(
        news_macro.get("macro_inflation_surprise_z", pd.Series(dtype=float))
    ).fillna(0.0) if "macro_inflation_surprise_z" in news_macro else 0.0

    # Factors 25-27: Intermarket (bond-equity, credit spread, yield curve)
    intermarket = _compute_intermarket_factors(latest_symbols, latest)
    scores["intermarket_bond_equity"] = scores["symbol"].map(
        intermarket.get("intermarket_bond_equity", pd.Series(dtype=float))
    ).fillna(0.0) if "intermarket_bond_equity" in intermarket else 0.0
    scores["intermarket_credit_spread"] = scores["symbol"].map(
        intermarket.get("intermarket_credit_spread", pd.Series(dtype=float))
    ).fillna(0.0) if "intermarket_credit_spread" in intermarket else 0.0
    scores["intermarket_yield_curve"] = scores["symbol"].map(
        intermarket.get("intermarket_yield_curve", pd.Series(dtype=float))
    ).fillna(0.0) if "intermarket_yield_curve" in intermarket else 0.0

    # Factors 28-29: Options (put-call extreme, VIX regime score)
    options = _compute_options_factors(latest_symbols, latest)
    scores["options_put_call_extreme"] = scores["symbol"].map(
        options.get("options_put_call_extreme", pd.Series(dtype=float))
    ).fillna(0.0) if "options_put_call_extreme" in options else 0.0
    scores["vix_regime_score"] = scores["symbol"].map(
        options.get("vix_regime_score", pd.Series(dtype=float))
    ).fillna(0.0) if "vix_regime_score" in options else 0.0

    # Factor 30: Congress trading activity
    congress = _compute_congress_factors(latest_symbols, latest)
    scores["congress_activity"] = scores["symbol"].map(
        congress.get("congress_activity", pd.Series(dtype=float))
    ).fillna(0.0) if "congress_activity" in congress else 0.0

    # Crash probability inverse -- not z-scored (scalar → zero variance).
    # Applied as multiplier post-composite via _crash_prediction_multiplier.

    # --- Cross-sectional z-score per factor ---
    # Use ddof=0 (population std) to avoid NaN for single-row universes.
    # For very small universes (< 5 symbols), z-scoring is statistically
    # meaningless, so use rank-normalization instead.
    factor_cols = [c for c in scores.columns if c != "symbol"]
    n_rows = len(scores)
    for col in factor_cols:
        vals = scores[col].astype(float)
        if n_rows < 5:
            # Rank-normalize: rank / N, centered around 0
            ranks = vals.rank(method="average", na_option="bottom")
            scores[col] = ((ranks / max(n_rows, 1)) - 0.5) * 2.0
        else:
            mean_v = vals.mean()
            std_v = vals.std(ddof=0)
            if std_v > 1e-10:
                scores[col] = (vals - mean_v) / std_v
            else:
                scores[col] = 0.0
        scores[col] = scores[col].clip(-3.0, 3.0)

    # --- Weighted composite with regime-conditional weights ---
    # Fix 20: Only count factors that contributed non-zero values to avoid
    # dead factors diluting the composite via their weight in total_weight.
    composite = pd.Series(0.0, index=scores.index)
    total_weight = 0.0
    used_factors = []
    for factor_name, weight in weights.items():
        if factor_name in scores.columns:
            factor_vals = scores[factor_name].fillna(0.0)
            if factor_vals.abs().sum() > 1e-10:
                composite += weight * factor_vals
                total_weight += weight
                used_factors.append(factor_name)

    if total_weight > 0:
        composite = composite / total_weight

    # --- Regime + crash exposure multiplier ---
    # crash_probability is applied ONLY via _crash_prediction_multiplier as a
    # risk-overlay exposure scaler (0.0–1.0). No separate additive/scaler
    # application — that would double-count.
    #
    regime_mult = REGIME_EXPOSURE.get(regime_label, 0.70)
    crash_mult = _crash_prediction_multiplier(df, cfg)
    exposure_mult = regime_mult * crash_mult
    composite = composite * exposure_mult

    # --- Build output signals ---
    out = []
    for i, (idx, row) in enumerate(latest.iterrows()):
        sym = row["symbol"]
        score = float(composite.iloc[i]) if i < len(composite) else 0.0
        ts = row.get("timestamp")
        ema_spread = float(scores.iloc[i].get("trend_ema_spread", 0.0)) if i < len(scores) else 0.0

        if score > min_score and ema_spread > -0.5:
            # Top contributing factors for reason string
            factor_contribs = []
            for f in used_factors:
                fval = float(scores.iloc[i].get(f, 0.0))
                fw = weights.get(f, 0.0)
                factor_contribs.append((f, fval * fw))
            factor_contribs.sort(key=lambda x: abs(x[1]), reverse=True)
            reasons = [f"{f}={v:.2f}" for f, v in factor_contribs[:5]]

            out.append({
                "timestamp": ts,
                "symbol": sym,
                "direction": "LONG",
                "score": score,
                "reason": f"v2|regime={regime_label}|" + "; ".join(reasons),
                # Preserve factor scores for meta-model
                **{f: float(scores.iloc[i].get(f, 0.0)) for f in factor_cols},
            })

    if not out:
        return _empty_signals()

    result = pd.DataFrame(out).sort_values("score", ascending=False)

    # --- Meta-model confidence filter (opt-in) ---
    meta_cfg = cfg.get("meta_model") or {}
    if meta_cfg.get("enabled", False):
        try:
            result = _apply_meta_model_filter(result, meta_cfg)
        except Exception as exc:
            logger.debug("[MF-V2] meta_model filter skipped: %s", exc)

    logger.info(
        "[MF-V2] %d LONG signals from %d symbols "
        "(regime=%s, exposure=%.2f, crash_mult=%.3f, active_factors=%d/%d)",
        len(result), len(latest), regime_label, exposure_mult,
        crash_mult, len(used_factors), len(weights),
    )
    return result


def _apply_meta_model_filter(
    signals: pd.DataFrame,
    meta_cfg: dict[str, Any],
) -> pd.DataFrame:
    """Load classifier, compute confidence, filter / scale signals."""
    model_path = meta_cfg.get("model_path")
    if not model_path or not os.path.exists(model_path):
        raise FileNotFoundError(f"meta_model path missing: {model_path}")

    min_conf = float(meta_cfg.get("min_confidence", 0.55))

    import joblib

    model = joblib.load(model_path)

    feature_cols = meta_cfg.get("feature_cols")
    if not feature_cols:
        feature_cols = [
            c for c in signals.columns
            if c.startswith(("trend_", "mom_", "mr_", "vol_", "vola_", "breadth_",
                             "sector_", "earnings_", "insider_", "news_", "macro_",
                             "intermarket_", "options_", "vix_", "crash_"))
        ]
    if not feature_cols:
        raise ValueError("meta_model: no feature columns available")

    missing = [c for c in feature_cols if c not in signals.columns]
    if missing:
        raise ValueError(f"meta_model: missing columns: {missing}")

    # Guard against silent feature poisoning: fillna(0.0) treats a data-feed
    # gap as a real standardized value, drifting confidence without warning.
    # Predict only on rows with complete features; rows with any NaN feature
    # get meta_confidence=NaN and are filtered by the min_conf gate below.
    feat_frame = signals[feature_cols]
    complete_mask = feat_frame.notna().all(axis=1).to_numpy()
    n_nan_rows = int((~complete_mask).sum())
    if n_nan_rows > 0:
        logger.warning(
            "[multifactor_v2.meta_model] %d/%d rows skipped due to NaN features",
            n_nan_rows,
            len(signals),
        )

    confidence = np.full(len(signals), np.nan, dtype=float)
    if complete_mask.any():
        X = feat_frame.loc[complete_mask].to_numpy()
        proba = model.predict_proba(X)
        if proba.ndim != 2 or proba.shape[1] < 2:
            raise ValueError(f"meta_model: unexpected shape {proba.shape}")
        confidence[complete_mask] = proba[:, 1]

    out = signals.copy()
    out["meta_confidence"] = confidence
    out = out.loc[np.nan_to_num(confidence, nan=-1.0) >= min_conf].copy()
    if out.empty:
        return out
    if "score" in out.columns:
        out["score"] = out["score"].astype(float) * out["meta_confidence"].astype(float)
    return out.reset_index(drop=True)


# ---------------------------------------------------------------------------
# Target positions — delegates to v1 (sizing is orthogonal to signal gen)
# ---------------------------------------------------------------------------


def compute_target_positions(*args: Any, **kwargs: Any) -> pd.DataFrame:
    """v2 target positions — delegates to v1.

    Sizing logic (score-proportional, HRP, BL) is configured via
    strategy_cfg["sizing_method"] and handled by v1's implementation.
    """
    return _v1_compute_target_positions(*args, **kwargs)


# ---------------------------------------------------------------------------
# ATR-regime adaptive exits
# ---------------------------------------------------------------------------

# ATR multipliers per regime
_STOP_ATR_MULT = {"bull": 3.0, "sideways": 2.0, "bear": 1.5, "crisis": 1.0}
_TRAIL_ATR_MULT = {"bull": 2.5, "sideways": 1.8, "bear": 1.2, "crisis": 0.8}
_TP_ATR_MULT = {"bull": 4.0, "sideways": 3.0, "bear": 2.0, "crisis": 1.5}


def _compute_atr(df: pd.DataFrame, symbol: str, window: int = 14) -> float:
    """Compute Average True Range for a symbol."""
    # Callers may pass frames without a timestamp column (e.g. already
    # latest-per-symbol snapshots). Skip the sort when timestamp is absent
    # so the function never raises KeyError on legitimate inputs.
    if "symbol" in df.columns:
        sym_df = df[df["symbol"] == symbol]
    else:
        sym_df = df
    if "timestamp" in sym_df.columns:
        sym_df = sym_df.sort_values("timestamp")
    if len(sym_df) < window + 1:
        return 0.0

    high = pd.to_numeric(sym_df.get("high", sym_df.get("close", pd.Series(dtype=float))), errors="coerce")
    low = pd.to_numeric(sym_df.get("low", sym_df.get("close", pd.Series(dtype=float))), errors="coerce")
    close = pd.to_numeric(sym_df.get("close", pd.Series(dtype=float)), errors="coerce")

    prev_close = close.shift(1)
    tr = pd.concat([
        (high - low).abs(),
        (high - prev_close).abs(),
        (low - prev_close).abs(),
    ], axis=1).max(axis=1)

    atr = tr.iloc[-window:].mean()
    return float(atr) if np.isfinite(atr) else 0.0


def check_exit_signals(
    current_positions: dict,
    prices_latest: pd.DataFrame,
    strategy_cfg: dict | None = None,
) -> pd.DataFrame:
    """ATR-regime adaptive exit signals.

    Uses regime-dependent ATR multipliers for stop-loss, trailing-stop,
    and take-profit. Includes momentum verification to reduce whipsaws.
    Falls back to v1 static exits if ATR computation fails.
    """
    cfg = strategy_cfg or {}
    exit_cfg = cfg.get("exits", {})
    exit_mode = exit_cfg.get("mode", "atr_regime")

    empty = pd.DataFrame(columns=["symbol", "direction", "exit_reason", "exit_qty_pct"])

    if not current_positions or prices_latest is None or prices_latest.empty:
        return empty

    # Fall back to static exits if configured
    if exit_mode == "static":
        from src.assembled_core.strategies.multifactor_v1 import (
            check_exit_signals as _v1_exits,
        )
        return _v1_exits(current_positions, prices_latest, strategy_cfg)

    # Detect regime for ATR multipliers
    regime = _detect_regime(prices_latest, cfg) if "symbol" in prices_latest.columns else "sideways"

    stop_mult = _STOP_ATR_MULT.get(regime, 2.0)
    trail_mult = _TRAIL_ATR_MULT.get(regime, 1.8)
    tp_mult = _TP_ATR_MULT.get(regime, 3.0)

    # Override from config if provided
    if "stop_atr_mult_by_regime" in exit_cfg:
        stop_mult = exit_cfg["stop_atr_mult_by_regime"].get(regime, stop_mult)
    if "trail_atr_mult_by_regime" in exit_cfg:
        trail_mult = exit_cfg["trail_atr_mult_by_regime"].get(regime, trail_mult)
    if "tp_atr_mult_by_regime" in exit_cfg:
        tp_mult = exit_cfg["tp_atr_mult_by_regime"].get(regime, tp_mult)

    atr_window = int(exit_cfg.get("atr_window", 14))
    momentum_verify = exit_cfg.get("momentum_verification", True)
    time_stop_days = int(exit_cfg.get("time_stop_days", 30))
    time_stop_min_return = float(exit_cfg.get("time_stop_min_return", 0.03))

    price_map = {}
    if "symbol" in prices_latest.columns and "close" in prices_latest.columns:
        price_map = dict(zip(prices_latest["symbol"].values, prices_latest["close"].values))

    exits = []
    for sym, pos in current_positions.items():
        qty = float(pos.get("qty", 0))
        if qty <= 0:
            continue
        avg_price = float(pos.get("avg_price", 0))
        hwm = float(pos.get("hwm", avg_price))
        if avg_price <= 0:
            continue

        current_price = float(price_map.get(sym, 0))
        if current_price <= 0:
            continue

        if current_price > hwm:
            hwm = current_price

        atr = _compute_atr(prices_latest, sym, atr_window)
        if atr <= 0:
            # Fallback to percentage-based stops
            atr = avg_price * 0.02  # ~2% as proxy

        # --- Stop-loss (ATR-based) ---
        stop_price = avg_price - stop_mult * atr
        if current_price <= stop_price:
            # Momentum verification: skip exit if RSI < 30 and EMA trending up
            if momentum_verify and _momentum_intact(prices_latest, sym):
                logger.debug("[MF-V2] %s: stop hit but momentum intact, holding", sym)
                continue
            exits.append({
                "symbol": sym,
                "direction": "FLAT",
                "exit_reason": f"stop_atr_{regime} ({current_price:.2f} <= {stop_price:.2f})",
                "exit_qty_pct": 1.0,
            })
            continue

        # --- Trailing stop (ATR-based on HWM) ---
        if hwm > avg_price:
            trail_price = hwm - trail_mult * atr
            if current_price <= trail_price:
                exits.append({
                    "symbol": sym,
                    "direction": "FLAT",
                    "exit_reason": f"trailing_atr_{regime} ({current_price:.2f} <= {trail_price:.2f}, hwm={hwm:.2f})",
                    "exit_qty_pct": 1.0,
                })
                continue

        # --- Take-profit (partial, ATR-based) ---
        tp_price = avg_price + tp_mult * atr
        if current_price >= tp_price:
            exits.append({
                "symbol": sym,
                "direction": "FLAT",
                "exit_reason": f"take_profit_atr_{regime} ({current_price:.2f} >= {tp_price:.2f})",
                "exit_qty_pct": 0.5,
            })
            continue

        # --- Time stop (zombie killer) ---
        days_held = int(pos.get("days_held", 0))
        if days_held > time_stop_days:
            return_pct = (current_price - avg_price) / avg_price if avg_price > 0 else 0.0
            if return_pct < time_stop_min_return:
                exits.append({
                    "symbol": sym,
                    "direction": "FLAT",
                    "exit_reason": f"time_stop ({days_held}d, return={return_pct:.2%} < {time_stop_min_return:.2%})",
                    "exit_qty_pct": 1.0,
                })
                continue

    if not exits:
        return empty
    return pd.DataFrame(exits)


def _momentum_intact(prices_latest: pd.DataFrame, symbol: str) -> bool:
    """Check if momentum is still intact (whipsaw protection).

    Returns True if RSI < 30 AND short-term EMA is above long-term EMA,
    suggesting the stop hit is a dip-in-uptrend rather than a reversal.
    """
    try:
        if "symbol" not in prices_latest.columns:
            return False
        sym_df = prices_latest[prices_latest["symbol"] == symbol]
        if sym_df.empty:
            return False

        row = sym_df.iloc[-1]
        rsi = float(row.get("ta_rsi_14_v1", 50.0))
        if rsi >= 30:
            return False

        # Check EMA trend
        ema_spread = float(row.get("trend_ema_spread", 0.0))
        if ema_spread <= 0:
            return False

        return True
    except Exception:
        return False


__all__ = ["compute_signals", "compute_target_positions", "check_exit_signals"]
