"""STRATEGY-V2: 31-factor multi-factor strategy with regime-conditional weights.

Active factors (31):
  - Trend (1-4): EMA spread, MA200 position, ADX strength, MACD histogram
  - Momentum (5-7): RSI centered, volume-weighted momentum, OBV trend
  - Mean-reversion (8-9, 16-17): Bollinger %B, Stochastic, 3d reversal, RSI extreme
  - Volume (10-11): abnormal volume, tick imbalance
  - Volatility (12-13): regime score, VoV penalty
  - Breadth (14-15): pct above MA, advance-decline slope
  - Sector (18): rotation bias
  - Earnings/Insider (19-20): EPS surprise z, insider activity score
  - News/Macro (21-24): sentiment, volume spike, growth momentum, inflation
  - Intermarket (25-27): bond-equity divergence, credit spread, yield curve
  - Options (28-29): put-call extreme, VIX regime score
  - Congress (30): congressional trading activity
  - Geo (31): geo-political risk composite (GPR index + ACLED intensity)

Crash probability is applied as a multiplicative scaler on the composite score,
not as a z-scored additive factor.

All 30 factors are now wired to their data sources. Factors gracefully degrade
to 0.0 when external data is unavailable (no dilution — zero-variance factors
are excluded from the composite via the dead-factor filter).

Factor 31 (meta-model confidence) is a multiplicative filter, not an additive
summand. It gates signals via a min-confidence threshold and scales scores.

Regime-conditional weights are loaded from configs/factor_weights_by_regime.json
(generated by scripts/train_regime_weights.py). If unavailable, default v2
weights from the factor contract are used.

Exit management: ATR-regime adaptive stops (stop-loss, trailing, take-profit)
with momentum verification for whipsaw protection.

Selection: strategy.name = "multifactor_v2" in configs/app.yaml.
"""

from __future__ import annotations

import json
import logging
from collections import OrderedDict
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from src.assembled_core.strategies.multifactor_v2_constants import (
    DD_DAMPER_DAYS,
    DD_DAMPER_FACTOR,
    DD_MDD_THRESHOLD,
    FACTOR_CLIP_MAX,
    FACTOR_CLIP_MIN,
    FACTOR_ZERO_VARIANCE_EPS,
    GPR_BASELINE_NORM,
    HMM_CACHE_MAXSIZE,
    RANK_NORM_SCALE,
    REGIME_CACHE_MAX_CONFIGS,
    SAFE_DIVIDE_DEFAULT,
    SAFE_DIVIDE_EPS,
    SMALL_UNIVERSE_THRESHOLD,
    STD_ZERO_REPLACE,
    YIELD_CURVE_CAP_DEFAULT,
    YIELD_CURVE_INVERSION_FRACTION,
    YIELD_CURVE_INVERSION_MIN_HISTORY,
    YIELD_CURVE_LOOKBACK_DAYS,
    VIX_CAP_ELEVATED,
    VIX_CAP_EXTREME,
    VIX_CAP_CRISIS,
    VIX_CAP_MILD,
    VIX_THRESHOLD_ELEVATED,
    VIX_THRESHOLD_EXTREME,
    VIX_THRESHOLD_CRISIS,
    VIX_THRESHOLD_MILD,
)
from src.assembled_core.strategies.multifactor_v1 import (
    REGIME_EXPOSURE,
    _abnormal_volume_score,
    _bollinger_score,
    _compute_breadth_score,
    _compute_ema_spread,
    _crash_prediction_multiplier,
    _empty_signals,
    _ma_position,
    _obv_trend,
    _rsi_score,
    _safe_col,
    _stochastic_score,
    _volatility_regime_score,
    _vov_penalty,
)
from src.assembled_core.strategies.multifactor_v1 import (
    compute_target_positions as _v1_compute_target_positions,
)

import datetime as _dt
import threading

logger = logging.getLogger(__name__)

STRATEGY_VERSION = "v2"
VERSION = "multifactor_v2.4.0"


# ---------------------------------------------------------------------------
# Utility: safe division (avoids ZeroDivisionError on tiny denominators)
# ---------------------------------------------------------------------------


def safe_divide(
    num: float,
    denom: float,
    default: float = SAFE_DIVIDE_DEFAULT,
) -> float:
    """Divide num by denom; return *default* when |denom| < SAFE_DIVIDE_EPS.

    Use this wherever inline division could silently produce inf/NaN when
    feed data is missing or degenerate.  Returning 0.0 (neutral) is
    consistent with the project-wide fillna(0) policy for missing factors.
    """
    if abs(denom) < SAFE_DIVIDE_EPS:
        return default
    return num / denom


# ---------------------------------------------------------------------------
# Bounded LRU cache for HMM market-return computations (Item 3)
# ---------------------------------------------------------------------------


class _BoundedCache:
    """Thread-safe bounded dict with LRU eviction.

    Replaces a plain dict that would grow without bound when the universe
    cycles through many (model_path, symbols) combinations over a long
    process lifetime.  maxsize matches HMM_CACHE_MAXSIZE from constants.
    """

    def __init__(self, maxsize: int = HMM_CACHE_MAXSIZE) -> None:
        self._maxsize = maxsize
        self._store: OrderedDict = OrderedDict()
        self._lock = __import__("threading").Lock()

    def get(self, key: Any, default: Any = None) -> Any:
        with self._lock:
            if key not in self._store:
                return default
            self._store.move_to_end(key)
            return self._store[key]

    def set(self, key: Any, value: Any) -> None:
        with self._lock:
            if key in self._store:
                self._store.move_to_end(key)
            self._store[key] = value
            if len(self._store) > self._maxsize:
                self._store.popitem(last=False)  # evict oldest

    def clear(self) -> None:
        with self._lock:
            self._store.clear()

    def __contains__(self, key: Any) -> bool:
        with self._lock:
            return key in self._store

    def __len__(self) -> int:
        with self._lock:
            return len(self._store)


# ---------------------------------------------------------------------------
# Drawdown self-damper — module-level state updated by paper runner / backtest
# ---------------------------------------------------------------------------
# IMPORTANT (Item 6): _DD_DAMPER is module-global state shared across all
# callers in the same Python process.  This design is intentional for the
# single-strategy paper runner, but it means:
#   - Concurrent backtests in the same process contaminate each other.
#   - Always call reset_dd_damper() between isolated backtest runs.
# If multi-strategy support is needed, move damper state into a per-instance
# context object (e.g. ctx.strategy_state["dd_damper"]).
_DD_LOCK = threading.Lock()
_DD_DAMPER: dict[str, Any] = {
    "peak_equity": 1.0,
    "current_equity": 1.0,
    "damper_active": False,
    "damper_until": None,  # datetime.date
    "mdd_threshold": DD_MDD_THRESHOLD,
    "damper_days": DD_DAMPER_DAYS,
    "damper_factor": DD_DAMPER_FACTOR,
}


def update_drawdown_damper(
    current_equity: float, as_of: "_dt.date | None" = None
) -> bool:
    """Update the module-level drawdown damper state.

    Call this daily from paper runner or backtest after equity is updated.
    Returns True if damper just activated.
    """
    today = as_of or _dt.date.today()
    with _DD_LOCK:
        state = _DD_DAMPER
        if current_equity > state["peak_equity"]:
            state["peak_equity"] = current_equity
        state["current_equity"] = current_equity

        # Deactivate expired damper
        if (
            state["damper_active"]
            and state["damper_until"]
            and today > state["damper_until"]
        ):
            state["damper_active"] = False
            state["damper_until"] = None
            logger.info("[MF-V2] Drawdown damper expired — exposure restored")

        # Activate if MDD threshold breached and damper not already running
        peak = state["peak_equity"]
        if peak > 0:
            mdd = (peak - current_equity) / peak
            if mdd >= state["mdd_threshold"] and not state["damper_active"]:
                state["damper_active"] = True
                state["damper_until"] = today + _dt.timedelta(days=state["damper_days"])
                logger.warning(
                    "[MF-V2] MDD %.1f%% >= %.1f%% — damper ON (×%.1f) until %s",
                    mdd * 100,
                    state["mdd_threshold"] * 100,
                    state["damper_factor"],
                    state["damper_until"],
                )
                return True
    return False


# ---------------------------------------------------------------------------
# Default v2 factor weights (used when regime weights file is unavailable)
# ---------------------------------------------------------------------------

DEFAULT_V2_WEIGHTS: dict[str, float] = {
    # --- TA factors (1-17): 60% total (Pfad B: reduced from 73%) ---
    "trend_ema_spread": 0.08,  # was 0.10
    "trend_ma200_position": 0.06,  # was 0.07
    "trend_adx_strength": 0.04,  # was 0.05
    "trend_macd_hist": 0.04,  # was 0.05
    "mom_rsi_centered": 0.05,  # was 0.06
    "mom_volume_weighted": 0.04,  # was 0.05
    "mom_obv_trend": 0.03,
    "mr_bollinger_pctb": 0.03,  # was 0.04
    "mr_stoch_oversold": 0.03,
    "vol_abnormal": 0.02,  # was 0.03
    "vol_tick_imbalance": 0.02,  # was 0.03
    "vola_regime_score": 0.03,
    "vola_vov_penalty": 0.03,
    "breadth_above_ma": 0.03,  # was 0.04
    "breadth_ad_line": 0.03,
    "mr_zscore_reversal_3d": 0.02,  # was 0.03
    "mr_rsi_extreme_uptrend": 0.02,  # was 0.03
    # --- Sector (18) ---
    "sector_rotation_bias": 0.04,
    # --- Earnings/Insider (19-20) ---
    "earnings_surprise_z": 0.03,
    "insider_activity_score": 0.02,
    # --- News/Macro (21-24): 8% total (was 3%) ---
    "news_sentiment_7d": 0.05,  # was 0.02
    "news_volume_spike": 0.03,  # was 0.01
    "macro_growth_momentum": 0.03,  # was 0.02
    "macro_inflation_surprise": 0.02,  # was 0.01
    # --- Intermarket (25-27): 8% total (was 6%) ---
    "intermarket_bond_equity": 0.03,  # was 0.02
    "intermarket_credit_spread": 0.03,  # was 0.02
    "intermarket_yield_curve": 0.02,
    # --- Options (28-29) ---
    "options_put_call_extreme": 0.02,
    "vix_regime_score": 0.01,  # was 0.02
    # --- Congress (30) ---
    "congress_activity": 0.02,
    # --- Geo composite (31): NEW — Pfad B ---
    "geo_risk_composite": 0.05,
    # NOTE: crash_probability_inverse is applied as a multiplicative scaler
    # on the final composite, not as an additive factor.
    # Sum = 1.00  (TA=0.60, sector=0.04, earn+ins=0.05, news/macro=0.10,
    #              intermarket=0.08, options=0.03, congress=0.02, geo=0.05)
    # Pfad B 2026-05-05: news+macro 3%→10%, intermarket 6%→8%, geo +5%,
    #                    TA reduced 73%→60%, vix_regime 2%→1%.
}

# ---------------------------------------------------------------------------
# Regime weights cache (Item 2)
# ---------------------------------------------------------------------------
# The cache is keyed by (config_path, file_mtime) so that:
#   a) stale entries are evicted when the JSON file changes on disk, and
#   b) the cache is bounded (REGIME_CACHE_MAX_CONFIGS entries max) to
#      prevent unlimited growth when many distinct paths are used.
#
# clear_regime_cache() is still provided for explicit runtime invalidation
# (e.g. from tests or after a weights retrain).

_REGIME_WEIGHTS_CACHE: _BoundedCache = _BoundedCache(maxsize=REGIME_CACHE_MAX_CONFIGS)
# Cache for HMM regime model objects: key = (str(path), mtime_float) to auto-invalidate
# when the model file is updated on disk. Uses the same _BoundedCache infrastructure
# as regime weights — evicts oldest entry when maxsize is exceeded.
_HMM_MODEL_CACHE: _BoundedCache = _BoundedCache(maxsize=HMM_CACHE_MAXSIZE)


def _load_regime_weights(cfg: dict[str, Any]) -> dict[str, dict[str, float]] | None:
    """Load regime-conditional factor weights from JSON file.

    Returns None if the file is missing or unparseable (defensive).

    Cache key = (path, mtime) so the cache auto-invalidates when the
    weights file is updated on disk without requiring an explicit clear.
    """
    path = cfg.get("regime_weights_path", "configs/factor_weights_by_regime.json")
    _p = Path(path)
    if not _p.is_file():
        logger.debug("[MF-V2] Regime weights file not found: %s", path)
        return None

    try:
        mtime = _p.stat().st_mtime
    except OSError:
        mtime = 0.0
    cache_key = (path, mtime)

    cached = _REGIME_WEIGHTS_CACHE.get(cache_key)
    if cached is not None:
        return cached

    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        # Validate: must have at least one regime key with a dict value
        regimes = {
            k: v
            for k, v in data.items()
            if isinstance(v, dict) and not k.startswith("_")
        }
        if not regimes:
            return None
        _REGIME_WEIGHTS_CACHE.set(cache_key, regimes)
        logger.info(
            "[MF-V2] Loaded regime weights for regimes: %s", list(regimes.keys())
        )
        return regimes
    except Exception as exc:
        logger.debug("[MF-V2] Failed to load regime weights: %s", exc)
        return None


def clear_regime_cache() -> None:
    """Invalidate the regime-weights cache so next call reloads from disk.

    Call this after updating the regime weights JSON file at runtime so
    the new weights take effect without restarting the process.
    Note: mtime-based auto-invalidation handles routine file updates;
    call this explicitly only when the path itself changes or in tests.
    """
    _REGIME_WEIGHTS_CACHE.clear()
    logger.info("[MF-V2] Regime weights cache cleared — will reload on next call")


def reset_dd_damper() -> None:
    """Reset the module-level drawdown damper to its initial state.

    Useful between isolated backtest runs in the same Python process to
    prevent cross-contamination of damper state.
    """
    with _DD_LOCK:
        _DD_DAMPER["peak_equity"] = 1.0
        _DD_DAMPER["current_equity"] = 1.0
        _DD_DAMPER["damper_active"] = False
        _DD_DAMPER["damper_until"] = None
    logger.info("[MF-V2] Drawdown damper reset to initial state")


def _get_weights_for_regime(
    regime_label: str,
    cfg: dict[str, Any],
) -> dict[str, float]:
    """Return factor weights for the given regime, or defaults."""
    regime_weights = _load_regime_weights(cfg)
    if regime_weights and regime_label in regime_weights:
        return regime_weights[regime_label]
    return DEFAULT_V2_WEIGHTS


# ---------------------------------------------------------------------------
# Regime detection (reuses v1 logic)
# ---------------------------------------------------------------------------


def _detect_regime(df: pd.DataFrame, cfg: dict[str, Any]) -> str:
    """Detect current market regime label."""
    # Try pre-trained HMM model first (MultiFeatureRegimeHMM, 2D: return+vol_20d)
    try:
        from pathlib import Path as _Path
        from src.assembled_core.ml.regime_hmm import MultiFeatureRegimeHMM

        _hmm_path = (
            _Path(__file__).parents[3] / "models" / "regime_hmm_4state_spy.joblib"
        )
        if _hmm_path.exists() and "close" in df.columns and "timestamp" in df.columns:
            _hmm_cache_key = (str(_hmm_path), _hmm_path.stat().st_mtime)
            _hmm = _HMM_MODEL_CACHE.get(_hmm_cache_key)
            if _hmm is None:
                _hmm = MultiFeatureRegimeHMM.load(_hmm_path)
                _HMM_MODEL_CACHE.set(_hmm_cache_key, _hmm)
            if "symbol" in df.columns:
                _px = df.pivot_table(
                    index="timestamp", columns="symbol", values="close", aggfunc="last"
                )
                _mkt = _px.mean(axis=1)
            else:
                _mkt = df.set_index("timestamp")["close"]
            _mkt = _mkt.sort_index().dropna()
            _log_ret = np.log((_mkt / _mkt.shift(1)).clip(lower=1e-10)).dropna()
            _vol_20d = _log_ret.rolling(20, min_periods=20).std().dropna()
            _log_ret = _log_ret.loc[_vol_20d.index]
            if len(_log_ret) >= 20:
                _feat = pd.DataFrame(
                    {"daily_return": _log_ret.values, "realized_vol": _vol_20d.values},
                    index=_log_ret.index,
                )
                _regimes = _hmm.predict_regime(_feat)
                if len(_regimes) > 0:
                    return str(_regimes.iloc[-1])
    except Exception as _exc:
        logger.debug("[multifactor_v2] HMM regime prediction failed: %s", _exc)

    try:
        from src.assembled_core.risk.regime_models import build_regime_state

        regime_df = build_regime_state(df)
        if regime_df is not None and not regime_df.empty:
            label = str(regime_df.iloc[-1].get("regime_label", "neutral")).lower()
            return label
    except Exception as _exc:
        logger.debug("[multifactor_v2] build_regime_state failed: %s", _exc)

    # Fallback: breadth-based
    breadth = _compute_breadth_score(df)
    if breadth < -0.4:
        return "bear"
    if breadth < -0.1:
        return "sideways"
    if breadth > 0.3:
        return "bull"
    return "sideways"


# ---------------------------------------------------------------------------
# New factor computations (factors 16-29)
# ---------------------------------------------------------------------------


def _compute_breadth_ad_slope(df: pd.DataFrame) -> float:
    """Factor 15: Advance-decline ratio slope (5-day).

    Counts symbols where close > close_5d_ago (advances) vs
    close < close_5d_ago (declines). Returns AD ratio centered
    around 0: ratio = advances / (advances + declines), score = (ratio - 0.5) * 2.
    This is genuinely different from breadth_above_ma (pct above MA50).
    """
    if df.empty or "symbol" not in df.columns or "close" not in df.columns:
        return 0.0
    try:
        sorted_df = df.sort_values("timestamp")
        latest = sorted_df.groupby("symbol", group_keys=False).tail(1)
        hist_5d = sorted_df.groupby("symbol", group_keys=False).nth(-6)

        if latest.empty or hist_5d.empty:
            return 0.0

        latest_prices = latest.set_index("symbol")["close"].astype(float)
        hist_prices = hist_5d.set_index("symbol")["close"].astype(float)
        common = latest_prices.index.intersection(hist_prices.index)
        if len(common) < 2:
            return 0.0

        advances = (latest_prices[common] > hist_prices[common]).sum()
        declines = (latest_prices[common] < hist_prices[common]).sum()
        total = advances + declines
        if total == 0:
            return 0.0
        ratio = float(advances) / float(total)
        return (ratio - 0.5) * 2.0
    except Exception as _exc:
        logger.debug("[MF-V2] _compute_breadth_ad_slope failed: %s", _exc)
        return 0.0


def _compute_mr_zscore_reversal_3d(df: pd.DataFrame) -> pd.Series:
    """Factor 16: 3-day return z-score inverted (oversold = positive)."""
    try:
        from src.assembled_core.features.mean_reversion_factors import (
            compute_mean_reversion_factors,
        )

        mr_df = compute_mean_reversion_factors(df)
        if mr_df is not None and "mr_zscore_reversal_3d" in mr_df.columns:
            latest = (
                mr_df.sort_values("timestamp")
                .groupby("symbol", group_keys=False)
                .tail(1)
            )
            return latest.set_index("symbol")["mr_zscore_reversal_3d"]
    except Exception as exc:
        logger.debug("[MF-V2] mr_zscore_reversal_3d unavailable: %s", exc)
    return pd.Series(dtype=float)


def _compute_mr_rsi_extreme_uptrend(df: pd.DataFrame) -> pd.Series:
    """Factor 17: RSI < 30 in uptrend signal."""
    try:
        from src.assembled_core.features.mean_reversion_factors import (
            compute_mean_reversion_factors,
        )

        mr_df = compute_mean_reversion_factors(df)
        if mr_df is not None and "mr_rsi_extreme_uptrend" in mr_df.columns:
            latest = (
                mr_df.sort_values("timestamp")
                .groupby("symbol", group_keys=False)
                .tail(1)
            )
            return latest.set_index("symbol")["mr_rsi_extreme_uptrend"]
    except Exception as exc:
        logger.debug("[MF-V2] mr_rsi_extreme_uptrend unavailable: %s", exc)
    return pd.Series(dtype=float)


def _compute_sector_rotation_bias(
    df: pd.DataFrame,
    latest_symbols: list[str],
    cfg: dict[str, Any],
) -> pd.Series:
    """Factor 18: Sector rotation bias per symbol.

    Maps each symbol to its GICS sector via security_meta.csv, then looks up
    the sector score from the sector_rotation module. Top-3 sectors get a
    boost (1.0), bottom-2 get penalty (-1.0), rest neutral (0.0).
    """
    try:
        meta_path = cfg.get("security_meta_path", "configs/security_meta.csv")
        if not Path(meta_path).is_file():
            return pd.Series(0.0, index=latest_symbols)

        meta = pd.read_csv(meta_path, dtype={"symbol": str, "sector": str})
        sym_to_sector = dict(zip(meta["symbol"], meta["sector"]))

        from src.assembled_core.signals.sector_rotation import (
            SECTOR_ETFS,
            SECTOR_NAMES,
            compute_sector_scores,
        )

        # Extract sector ETF prices from df if available
        sector_syms = [s for s in SECTOR_ETFS if s in set(df["symbol"])]
        if len(sector_syms) < 3:
            return pd.Series(0.0, index=latest_symbols)

        sector_prices = df[df["symbol"].isin(sector_syms)].copy()
        spy_prices = df[df["symbol"] == "SPY"].copy()
        if spy_prices.empty:
            return pd.Series(0.0, index=latest_symbols)

        scores_df = compute_sector_scores(sector_prices, spy_prices)
        if scores_df.empty:
            return pd.Series(0.0, index=latest_symbols)

        # Get latest row scores
        latest_scores = scores_df.iloc[-1]
        etf_scores = {}
        for etf in sector_syms:
            col = f"{etf}_score"
            if col in latest_scores.index:
                etf_scores[etf] = float(latest_scores[col])

        if not etf_scores:
            return pd.Series(0.0, index=latest_symbols)

        # Rank sectors: top 3 = +1, bottom 2 = -1, rest = 0
        sorted_etfs = sorted(etf_scores, key=etf_scores.get, reverse=True)
        top_sectors = {SECTOR_NAMES.get(e, "") for e in sorted_etfs[:3]}
        bottom_sectors = {SECTOR_NAMES.get(e, "") for e in sorted_etfs[-2:]}

        result = {}
        for sym in latest_symbols:
            sector = sym_to_sector.get(sym, "")
            if sector in top_sectors:
                result[sym] = 1.0
            elif sector in bottom_sectors:
                result[sym] = -1.0
            else:
                result[sym] = 0.0

        return pd.Series(result)
    except Exception as exc:
        logger.debug("[MF-V2] sector_rotation_bias unavailable: %s", exc)
        return pd.Series(0.0, index=latest_symbols)


def _compute_earnings_insider_factors(
    latest_symbols: list[str],
    cfg: dict[str, Any],
    as_of: pd.Timestamp | None = None,
) -> tuple[pd.Series, pd.Series]:
    """Factors 19-20: earnings surprise z, insider activity score."""
    try:
        from src.assembled_core.features.earnings_insider_wrapper import (
            compute_earnings_insider_factors,
        )

        as_of = (as_of or pd.Timestamp.now()).normalize()
        from src.assembled_core.data.altdata_loader import (  # noqa: PLC0415
            load_earnings_history,
            load_insider_filings,
        )

        earnings_df = load_earnings_history(latest_symbols, as_of, lookback_days=90)
        filings_df = load_insider_filings(latest_symbols, as_of, lookback_days=90)
        result = compute_earnings_insider_factors(
            as_of, latest_symbols, earnings_df, filings_df
        )
        if result is not None and not result.empty:
            earn_z = result.get("earnings_surprise_z", pd.Series(dtype=float))
            # Column is "insider_activity_score" (not "insider_activity_z")
            insider = result.get("insider_activity_score", pd.Series(dtype=float))
            return earn_z, insider
    except Exception as exc:
        logger.debug("[MF-V2] earnings/insider factors unavailable: %s", exc)
    empty = pd.Series(dtype=float)
    return empty, empty


def _compute_news_macro_factors(
    latest_symbols: list[str],
    cfg: dict[str, Any],
    as_of: pd.Timestamp | None = None,
) -> dict[str, pd.Series]:
    """Factors 21-24: news sentiment, volume spike, macro growth, inflation."""
    result: dict[str, pd.Series] = {}
    try:
        from src.assembled_core.features.news_macro_wrapper import (
            compute_news_macro_factors,
        )

        as_of = (as_of or pd.Timestamp.now()).normalize()
        from src.assembled_core.data.altdata_loader import (  # noqa: PLC0415
            load_macro_indicators,
            load_news_sentiment,
        )

        news_df = load_news_sentiment(latest_symbols, as_of, lookback_days=30)
        macro_df = load_macro_indicators(as_of, lookback_days=365)
        out = compute_news_macro_factors(as_of, latest_symbols, news_df, macro_df)
        if out is not None and not out.empty:
            for col in [
                "news_sentiment_7d_z",
                "news_volume_spike_z",
                "macro_growth_momentum_z",
                "macro_inflation_surprise_z",
            ]:
                if col in out.columns:
                    result[col] = out[col]
    except Exception as exc:
        logger.debug("[MF-V2] news/macro factors unavailable: %s", exc)
    return result


def _compute_intermarket_factors(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factors 25-27: bond-equity divergence, credit spread, yield curve.

    Strategy:
    1. Read pre-merged columns from latest (populated by trading_cycle).
    2. If missing, fetch directly via build_intermarket_factors().
    Universal factors — same value per date, broadcast to all symbols.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )

    # --- Path 1: columns already in latest (from trading_cycle merge) ---
    col_map = {
        "intermarket_bond_equity": "bond_equity_divergence_flag",
        "intermarket_credit_spread": "credit_spread_change_5d",
        "intermarket_yield_curve": "yield_curve_slope",
    }
    found_any = False
    for factor_name, src_col in col_map.items():
        if src_col in latest.columns:
            vals = pd.to_numeric(latest[src_col], errors="coerce").fillna(0.0)
            result[factor_name] = pd.Series(vals.values, index=sym_idx.values)
            found_any = True

    if found_any:
        logger.debug("[MF-V2] intermarket factors: %d read from panel", len(result))
        return result

    # --- Path 2: fetch directly ---
    try:
        from src.assembled_core.features.intermarket_factors import (
            build_intermarket_factors,
        )

        im = build_intermarket_factors()
        if not im.empty:
            last_row = im.iloc[-1]
            for factor_name, src_col in col_map.items():
                val = (
                    float(last_row.get(src_col, 0.0)) if src_col in im.columns else 0.0
                )
                result[factor_name] = pd.Series(val, index=sym_idx.values)
            logger.debug(
                "[MF-V2] intermarket factors: fetched %d directly", len(result)
            )
    except Exception as exc:
        logger.debug("[MF-V2] intermarket factors unavailable: %s", exc)
    return result


def _compute_options_factors(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factors 28-29: put-call extreme, VIX regime z-score.

    Fetches VIX/VIX3M/PCR from CBOESource, computes regime factors.
    Universal factors — same value per date, broadcast to all symbols.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )

    try:
        from src.assembled_core.data.sources.cboe_source import CBOESource
        from src.assembled_core.features.options_derived_signals import (
            build_options_regime_factors,
        )

        cboe = CBOESource()
        cboe_df = cboe.fetch_options_regime_data()
        if not cboe_df.empty:
            opts = build_options_regime_factors(cboe_df)
            if not opts.empty:
                last_row = opts.iloc[-1]
                pcr_extreme = float(last_row.get("equity_put_call_extreme", 0.0))
                vix_z = float(last_row.get("vix_zscore_252d", 0.0))
                result["options_put_call_extreme"] = pd.Series(
                    pcr_extreme, index=sym_idx.values
                )
                result["vix_regime_score"] = pd.Series(vix_z, index=sym_idx.values)
                logger.debug(
                    "[MF-V2] options factors: pcr_extreme=%.2f, vix_z=%.2f",
                    pcr_extreme,
                    vix_z,
                )
    except Exception as exc:
        logger.debug("[MF-V2] options factors unavailable: %s", exc)
    return result


def _compute_congress_factors(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factor 30: congressional trading activity score.

    Reads pre-merged congress columns from the panel (populated by
    trading_cycle when include_congress=True). Per-symbol factor.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )

    try:
        # Congress features are per-symbol — read from panel if available
        count_col = "congress_trade_count_90d"
        amount_col = "congress_total_amount_90d"

        if count_col in latest.columns:
            count_vals = pd.to_numeric(latest[count_col], errors="coerce").fillna(0.0)
            amount_vals = pd.to_numeric(
                latest.get(amount_col, pd.Series(0.0, index=latest.index)),
                errors="coerce",
            ).fillna(0.0)
            # Composite: normalize count + log(1+amount) as activity score
            activity = count_vals + np.log1p(amount_vals.abs()) / 10.0
            result["congress_activity"] = pd.Series(
                activity.values, index=sym_idx.values
            )
            logger.debug(
                "[MF-V2] congress factors: %d symbols with data", (count_vals > 0).sum()
            )
    except Exception as exc:
        logger.debug("[MF-V2] congress factors unavailable: %s", exc)
    return result


def _compute_geo_risk_composite(
    latest_symbols: list[str],
    latest: pd.DataFrame,
    as_of: pd.Timestamp | None = None,
) -> dict[str, pd.Series]:
    """Factor 31: geo-political risk composite (Pfad B).

    Priority:
    1. Pre-merged panel columns: gpr_index, acled_intensity, geo_risk_score.
    2. Live fetch via compute_gpr_from_fred (FRED API). DISABLED in backtest mode
       (when as_of is set) per F-B-1 BLOCKER fix: live fetch uses date.today()
       and would leak future data into backtest replays.
    3. Zero-fill (graceful degradation).

    Sign convention: positive score = higher geopolitical risk → bearish signal
    for equities. Negated before return so that high risk → negative factor input.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )

    # Path 1: pre-merged columns (populated by trading_cycle or panel build)
    gpr_cols = {
        "gpr_index": 1.0,  # Caldara-Iacoviello GPR index (higher = more risk)
        "acled_intensity": 0.5,  # ACLED conflict intensity (supplementary)
        "geo_risk_score": 1.0,  # generic geo risk column
    }
    composite_val: float | None = None
    for col, col_weight in gpr_cols.items():
        if col in latest.columns:
            vals = pd.to_numeric(latest[col], errors="coerce").fillna(0.0)
            if vals.abs().sum() > 1e-10:
                raw = float(vals.mean()) * col_weight
                composite_val = (composite_val or 0.0) + raw

    if composite_val is not None:
        # Normalize: GPR index ~100 at baseline; z-score it roughly
        # GPR_BASELINE_NORM: index ≈ 100 at baseline → z ≈ 2 (see constants)
        geo_z = safe_divide(composite_val, GPR_BASELINE_NORM, default=0.0)
        geo_z = float(np.clip(geo_z, FACTOR_CLIP_MIN, FACTOR_CLIP_MAX))
        # Negate: high geo risk → bearish for equities
        result["geo_risk_composite"] = pd.Series(-geo_z, index=sym_idx.values)
        logger.debug(
            "[MF-V2] geo composite (panel): val=%.2f z=%.2f", composite_val, geo_z
        )
        return result

    # Path 2: fetch live GPR from FRED (GPRC = historical, monthly series).
    # F-B-1 BLOCKER fix: SKIP entirely in backtest mode (when as_of is set).
    # Reason: date.today()-based fetch would inject future data into replays.
    if as_of is not None:
        logger.debug(
            "[MF-V2] geo composite: as_of=%s set (backtest mode), skipping live FRED fetch, zero-fill",
            as_of,
        )
        result["geo_risk_composite"] = pd.Series(0.0, index=sym_idx.values)
        return result

    try:
        import datetime as _dt
        from src.assembled_core.features.geopolitical_features import (
            compute_gpr_from_fred,
        )
        from src.assembled_core.data.sources.fred_source import fetch_fred_series

        _end = _dt.date.today().isoformat()
        _start = (
            (_dt.date.today()).replace(year=_dt.date.today().year - 5)
        ).isoformat()
        _fred_df = fetch_fred_series(["GPRC"], _start, _end)
        if not _fred_df.empty:
            _gpr_vals = (
                _fred_df[_fred_df["series_id"] == "GPRC"]
                .set_index("timestamp")["value"]
                .sort_index()
                .dropna()
            )
            if len(_gpr_vals) >= 30:
                gpr_features = compute_gpr_from_fred(_gpr_vals, rolling_window=252)
                if not gpr_features.empty and "gpr_zscore" in gpr_features.columns:
                    current_z = float(gpr_features["gpr_zscore"].dropna().iloc[-1])
                    result["geo_risk_composite"] = pd.Series(
                        -current_z, index=sym_idx.values
                    )
                    logger.debug("[MF-V2] geo composite (FRED): z=%.2f", current_z)
                    return result
    except Exception as exc:
        logger.debug("[MF-V2] geo composite FRED fetch failed: %s", exc)

    # Path 3: zero-fill (factor excluded from composite by zero-variance guard)
    logger.debug("[MF-V2] geo composite: no data, zero-fill")
    result["geo_risk_composite"] = pd.Series(0.0, index=sym_idx.values)
    return result


def _compute_insider_cluster_factor(
    latest_symbols: list[str],
    latest: pd.DataFrame,
    as_of: pd.Timestamp | None = None,
) -> dict[str, pd.Series]:
    """Factor 32: Insider cluster buy/sell score (Cohen et al. 2012).

    Uses signals/insider_cluster.py which detects ≥3 insiders buying/selling
    within 30 days — a documented +2-4% p.a. alpha source.
    Reads pre-computed panel columns if available; falls back to live fetch.

    F-B-2 BLOCKER fix: live fetch (cluster_buy_score) uses date.today() and
    would leak future SEC Form-4 filings into backtest replays. DISABLED when
    as_of is set (backtest mode).
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )
    try:
        # Prefer pre-computed panel columns (populated by altdata pipeline)
        if "insider_cluster_score" in latest.columns:
            result["insider_cluster_score"] = pd.Series(
                pd.to_numeric(latest["insider_cluster_score"], errors="coerce")
                .fillna(0.0)
                .values,
                index=sym_idx.values,
            )
            return result

        # F-B-2 BLOCKER fix: skip live fetch in backtest mode (as_of set)
        if as_of is not None:
            logger.debug(
                "[MF-V2] insider_cluster_score: as_of=%s set, skipping live EDGAR fetch, zero-fill",
                as_of,
            )
            result["insider_cluster_score"] = pd.Series(0.0, index=sym_idx.values)
            return result

        # Fallback: call signal module directly (slow, one-by-one). Live mode only.
        from src.assembled_core.signals.insider_cluster import (
            cluster_buy_score,
        )  # noqa: PLC0415

        scores: dict[str, float] = {}
        for sym in latest_symbols[
            :20
        ]:  # limit live calls to top 20 to avoid rate limit
            try:
                val = cluster_buy_score(sym, days=30)
                scores[sym] = float(val) if val is not None else 0.0
            except Exception:
                scores[sym] = 0.0
        result["insider_cluster_score"] = pd.Series(scores)
        logger.debug("[MF-V2] insider cluster factor: %d symbols", len(scores))
    except Exception as exc:
        logger.debug("[MF-V2] insider cluster factor unavailable: %s", exc)
    return result


def _compute_pead_sue_factor(
    latest_symbols: list[str],
    latest: pd.DataFrame,
    as_of: pd.Timestamp | None = None,
) -> dict[str, pd.Series]:
    """Factor 33: PEAD/SUE — Post-Earnings-Announcement Drift via Standardized Unexpected Earnings.

    Bernard & Thomas (1989): one of the most robust market anomalies.
    +3-5% p.a. for long top decile / short bottom decile.
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )
    try:
        # Prefer pre-computed panel columns
        if "sue_score" in latest.columns:
            result["pead_sue_score"] = pd.Series(
                pd.to_numeric(latest["sue_score"], errors="coerce").fillna(0.0).values,
                index=sym_idx.values,
            )
            return result

        from src.assembled_core.signals.pead_sue import batch_sue  # noqa: PLC0415
        from src.assembled_core.data.altdata_loader import (
            load_earnings_history,
        )  # noqa: PLC0415

        as_of = (as_of or pd.Timestamp.now()).normalize()
        earnings_df = load_earnings_history(latest_symbols, as_of, lookback_days=90)
        if earnings_df is not None and not earnings_df.empty:
            sue_series = batch_sue(earnings_df, latest_symbols)
            if sue_series is not None:
                result["pead_sue_score"] = sue_series.reindex(
                    latest_symbols, fill_value=0.0
                )
                logger.debug(
                    "[MF-V2] PEAD/SUE: %d symbols with data",
                    (sue_series != 0).sum(),
                )
    except Exception as exc:
        logger.debug("[MF-V2] PEAD/SUE factor unavailable: %s", exc)
    return result


def _compute_buyback_drift_factor(
    latest_symbols: list[str],
    latest: pd.DataFrame,
    as_of: pd.Timestamp | None = None,
) -> dict[str, pd.Series]:
    """Factor 34: Buyback drift (Ikenberry et al.) — 60-90 day post-announcement momentum.

    +1-2% p.a. after 8-K buyback announcements. Orthogonal to insider signals.

    F-B-3 BLOCKER fix: live fetch (buyback_signal_score) uses date.today() and
    would leak future 8-K filings into backtest replays. DISABLED when as_of
    is set (backtest mode).
    """
    result: dict[str, pd.Series] = {}
    sym_idx = (
        latest["symbol"] if "symbol" in latest.columns else pd.Series(latest_symbols)
    )
    try:
        if "buyback_drift_score" in latest.columns:
            result["buyback_drift_score"] = pd.Series(
                pd.to_numeric(latest["buyback_drift_score"], errors="coerce")
                .fillna(0.0)
                .values,
                index=sym_idx.values,
            )
            return result

        # F-B-3 BLOCKER fix: skip live fetch in backtest mode
        if as_of is not None:
            logger.debug(
                "[MF-V2] buyback_drift_score: as_of=%s set, skipping live EDGAR fetch, zero-fill",
                as_of,
            )
            result["buyback_drift_score"] = pd.Series(0.0, index=sym_idx.values)
            return result

        from src.assembled_core.signals.buyback_drift import (
            buyback_signal_score,
        )  # noqa: PLC0415

        scores: dict[str, float] = {}
        for sym in latest_symbols[:30]:
            try:
                val = buyback_signal_score(sym)
                scores[sym] = float(val) if val is not None else 0.0
            except Exception:
                scores[sym] = 0.0
        result["buyback_drift_score"] = pd.Series(scores)
        logger.debug("[MF-V2] buyback drift factor: %d symbols", len(scores))
    except Exception as exc:
        logger.debug("[MF-V2] buyback drift factor unavailable: %s", exc)
    return result


def _compute_options_iv_factor(
    latest_symbols: list[str],
    latest: pd.DataFrame,
) -> dict[str, pd.Series]:
    """Factor 35 (Item 106): Options IV-skew score — ML feature, zero-weighted by default.

    IV-skew = implied vol of puts relative to calls.  Elevated skew signals
    institutional hedging activity — a forward-looking fear indicator orthogonal
    to TA / news factors.

    To activate in composite: add ``"options_iv_skew_score": 0.02`` to
    PFAD_B_WEIGHTS and reduce ``geo_risk_composite`` from 0.05 → 0.03.

    Data priority:
    1. Pre-computed ``options_iv_skew_score`` / ``iv_skew`` column in ``latest``.
    2. Live computation via ``signals/options_iv.iv_skew()`` (needs py_vollib).
    3. Zero-fill.
    """
    sym_idx = pd.Index(latest_symbols)
    result: dict[str, pd.Series] = {}

    for col in ("options_iv_skew_score", "iv_skew", "options_iv_skew"):
        if col in latest.columns:
            result["options_iv_skew_score"] = pd.Series(
                pd.to_numeric(latest[col], errors="coerce").values,
                index=sym_idx,
            ).fillna(0.0)
            return result

    try:
        from src.assembled_core.signals.options_iv import iv_skew  # noqa: PLC0415

        scores = [float(iv_skew(sym, None) or 0.0) for sym in latest_symbols]
        result["options_iv_skew_score"] = pd.Series(scores, index=sym_idx)
    except Exception as exc:
        logger.debug("[MF-V2] options_iv factor unavailable: %s", exc)

    if "options_iv_skew_score" not in result:
        result["options_iv_skew_score"] = pd.Series(0.0, index=sym_idx)
    return result


def _compute_crash_prob_inverse(df: pd.DataFrame, cfg: dict[str, Any]) -> float:
    """Factor 29: inverse crash probability (1 - crash_prob)."""
    crash_mult = _crash_prediction_multiplier(df, cfg)
    # crash_mult ranges from 0.0 (crash) to 1.0 (no crash)
    # Convert to z-score-like: 1.0 → +1, 0.0 → -3
    return (crash_mult - 0.5) * 4.0  # 1.0→+2.0, 0.5→0.0, 0.0→-2.0


# ---------------------------------------------------------------------------
# Main signal generation
# ---------------------------------------------------------------------------


def compute_signals(
    prices_with_features: pd.DataFrame,
    strategy_cfg: dict[str, Any] | None = None,
) -> pd.DataFrame:
    """Generate 30-factor signals with regime-conditional weights.

    All 30 factors are actively computed. Factors degrade gracefully to 0.0
    when external data is unavailable. Dead factors (zero variance) are
    excluded from the weighted composite to prevent dilution.

    Drop-in replacement for v1. Same input/output schema.
    """
    cfg = strategy_cfg or {}
    min_score = float(cfg.get("min_signal_score", 0.0))
    ema_fast = int(cfg.get("ema_fast") or 20)
    ema_slow = int(cfg.get("ema_slow") or 60)

    if prices_with_features.empty or "symbol" not in prices_with_features.columns:
        return _empty_signals()

    df = prices_with_features.copy()
    if "timestamp" not in df.columns:
        return _empty_signals()

    # Latest bar per symbol
    latest = (
        df.sort_values("timestamp").groupby("symbol", group_keys=False).tail(1).copy()
    )
    if latest.empty:
        return _empty_signals()

    latest_symbols = latest["symbol"].tolist()
    # Bar date: use latest timestamp in the panel as PIT anchor for altdata lookups.
    # This prevents Timestamp.now() look-ahead in backtest mode (factors 19-24, 33).
    _bar_as_of = pd.Timestamp(latest["timestamp"].max())

    # --- Detect regime ---
    regime_label = _detect_regime(df, cfg)
    weights = _get_weights_for_regime(regime_label, cfg)

    # --- Signal decay gate (policy-gated, shadow mode by default) ---
    from src.assembled_core.strategies.signal_decay_gate import (
        apply_multipliers as _apply_decay,
    )

    _decay_cfg = cfg.get("signal_decay", {}) or {}
    weights, _decay_multipliers = _apply_decay(
        dict(weights),
        enabled=bool(_decay_cfg.get("enabled", False)),
        stale_multiplier=float(_decay_cfg.get("stale_multiplier", 0.0)),
        report_path=(
            None
            if _decay_cfg.get("report_path") is None
            else __import__("pathlib").Path(_decay_cfg["report_path"])
        ),
    )

    logger.info(
        "[MF-V2] Regime=%s, %d weight entries, universe=%d symbols",
        regime_label,
        len(weights),
        len(latest_symbols),
    )

    # --- Compute raw factor values (factors 1-15 from v1) ---
    scores = pd.DataFrame({"symbol": latest["symbol"].values})
    scores.index = latest.index

    close = pd.to_numeric(latest.get("close", pd.Series(dtype=float)), errors="coerce")

    # Factors 1-4: Trend
    scores["trend_ema_spread"] = _compute_ema_spread(df, ema_fast, ema_slow)
    scores["trend_ma200_position"] = _ma_position(
        latest, close, "ta_ma_200_v1", fallback_window=200
    )
    scores["trend_adx_strength"] = _safe_col(latest, "ta_adx_v1", default=0.0) / 100.0
    scores["trend_macd_hist"] = _safe_col(latest, "ta_macd_hist_v1", default=0.0)

    # Factors 5-7: Momentum
    scores["mom_rsi_centered"] = _rsi_score(latest)
    scores["mom_volume_weighted"] = _safe_col(
        latest, "ta_vol_weighted_mom_20d_v1", default=0.0
    )
    scores["mom_obv_trend"] = _obv_trend(df)

    # Factors 8-9: Mean-reversion guard
    scores["mr_bollinger_pctb"] = _bollinger_score(latest)
    scores["mr_stoch_oversold"] = _stochastic_score(latest)

    # Factors 10-11: Volume
    scores["vol_abnormal"] = _abnormal_volume_score(latest)
    scores["vol_tick_imbalance"] = _safe_col(latest, "tick_imbalance_20d", default=0.5)

    # Factors 12-13: Volatility
    scores["vola_regime_score"] = _volatility_regime_score(latest)
    scores["vola_vov_penalty"] = _vov_penalty(latest)

    # Factors 14-15: Breadth (two genuinely different signals)
    scores["breadth_above_ma"] = _compute_breadth_score(df)
    scores["breadth_ad_line"] = _compute_breadth_ad_slope(df)

    # --- New v2 factors (16-29) — defensive, all return NaN on failure ---

    # Factors 16-17: Mean-reversion from sidecar module
    mr_16 = _compute_mr_zscore_reversal_3d(df)
    mr_17 = _compute_mr_rsi_extreme_uptrend(df)
    scores["mr_zscore_reversal_3d"] = (
        scores["symbol"].map(mr_16).fillna(0.0) if not mr_16.empty else 0.0
    )
    scores["mr_rsi_extreme_uptrend"] = (
        scores["symbol"].map(mr_17).fillna(0.0) if not mr_17.empty else 0.0
    )

    # Factor 18: Sector rotation
    sector_bias = _compute_sector_rotation_bias(df, latest_symbols, cfg)
    scores["sector_rotation_bias"] = (
        scores["symbol"].map(sector_bias).fillna(0.0) if not sector_bias.empty else 0.0
    )

    # Factors 19-20: Earnings + Insider
    earn_z, insider_z = _compute_earnings_insider_factors(
        latest_symbols, cfg, as_of=_bar_as_of
    )
    scores["earnings_surprise_z"] = (
        scores["symbol"].map(earn_z).fillna(0.0) if not earn_z.empty else 0.0
    )
    scores["insider_activity_score"] = (
        scores["symbol"].map(insider_z).fillna(0.0) if not insider_z.empty else 0.0
    )

    # Factors 21-24: News + Macro
    news_macro = _compute_news_macro_factors(latest_symbols, cfg, as_of=_bar_as_of)
    scores["news_sentiment_7d"] = (
        scores["symbol"]
        .map(news_macro.get("news_sentiment_7d_z", pd.Series(dtype=float)))
        .fillna(0.0)
        if "news_sentiment_7d_z" in news_macro
        else 0.0
    )
    scores["news_volume_spike"] = (
        scores["symbol"]
        .map(news_macro.get("news_volume_spike_z", pd.Series(dtype=float)))
        .fillna(0.0)
        if "news_volume_spike_z" in news_macro
        else 0.0
    )
    scores["macro_growth_momentum"] = (
        scores["symbol"]
        .map(news_macro.get("macro_growth_momentum_z", pd.Series(dtype=float)))
        .fillna(0.0)
        if "macro_growth_momentum_z" in news_macro
        else 0.0
    )
    scores["macro_inflation_surprise"] = (
        scores["symbol"]
        .map(news_macro.get("macro_inflation_surprise_z", pd.Series(dtype=float)))
        .fillna(0.0)
        if "macro_inflation_surprise_z" in news_macro
        else 0.0
    )

    # Factors 25-27: Intermarket (bond-equity, credit spread, yield curve)
    intermarket = _compute_intermarket_factors(latest_symbols, latest)
    scores["intermarket_bond_equity"] = (
        scores["symbol"]
        .map(intermarket.get("intermarket_bond_equity", pd.Series(dtype=float)))
        .fillna(0.0)
        if "intermarket_bond_equity" in intermarket
        else 0.0
    )
    scores["intermarket_credit_spread"] = (
        scores["symbol"]
        .map(intermarket.get("intermarket_credit_spread", pd.Series(dtype=float)))
        .fillna(0.0)
        if "intermarket_credit_spread" in intermarket
        else 0.0
    )
    scores["intermarket_yield_curve"] = (
        scores["symbol"]
        .map(intermarket.get("intermarket_yield_curve", pd.Series(dtype=float)))
        .fillna(0.0)
        if "intermarket_yield_curve" in intermarket
        else 0.0
    )

    # Factors 28-29: Options (put-call extreme, VIX regime score)
    options = _compute_options_factors(latest_symbols, latest)
    scores["options_put_call_extreme"] = (
        scores["symbol"]
        .map(options.get("options_put_call_extreme", pd.Series(dtype=float)))
        .fillna(0.0)
        if "options_put_call_extreme" in options
        else 0.0
    )
    scores["vix_regime_score"] = (
        scores["symbol"]
        .map(options.get("vix_regime_score", pd.Series(dtype=float)))
        .fillna(0.0)
        if "vix_regime_score" in options
        else 0.0
    )

    # Factor 30: Congress trading activity
    congress = _compute_congress_factors(latest_symbols, latest)
    scores["congress_activity"] = (
        scores["symbol"]
        .map(congress.get("congress_activity", pd.Series(dtype=float)))
        .fillna(0.0)
        if "congress_activity" in congress
        else 0.0
    )

    # Factor 31: Geo-political risk composite (Pfad B). F-B-1: pass as_of.
    geo = _compute_geo_risk_composite(latest_symbols, latest, as_of=_bar_as_of)
    scores["geo_risk_composite"] = (
        scores["symbol"]
        .map(geo.get("geo_risk_composite", pd.Series(dtype=float)))
        .fillna(0.0)
        if "geo_risk_composite" in geo
        else 0.0
    )

    # Factor 32: Insider cluster buy/sell (Cohen et al. 2012, +2-4% p.a. alpha). F-B-2: pass as_of.
    insider_cl = _compute_insider_cluster_factor(
        latest_symbols, latest, as_of=_bar_as_of
    )
    scores["insider_cluster_score"] = (
        scores["symbol"]
        .map(insider_cl.get("insider_cluster_score", pd.Series(dtype=float)))
        .fillna(0.0)
        if "insider_cluster_score" in insider_cl
        else 0.0
    )

    # Factor 33: PEAD/SUE — post-earnings drift (Bernard & Thomas 1989)
    pead = _compute_pead_sue_factor(latest_symbols, latest, as_of=_bar_as_of)
    scores["pead_sue_score"] = (
        scores["symbol"]
        .map(pead.get("pead_sue_score", pd.Series(dtype=float)))
        .fillna(0.0)
        if "pead_sue_score" in pead
        else 0.0
    )

    # Factor 34: Buyback drift (Ikenberry et al., 60-90d post-announcement). F-B-3: pass as_of.
    buyback = _compute_buyback_drift_factor(latest_symbols, latest, as_of=_bar_as_of)
    scores["buyback_drift_score"] = (
        scores["symbol"]
        .map(buyback.get("buyback_drift_score", pd.Series(dtype=float)))
        .fillna(0.0)
        if "buyback_drift_score" in buyback
        else 0.0
    )

    # Factor 35 (Item 106): Options IV-skew — institutional hedging signal.
    # Zero-weighted in composite by default; available as ML feature.
    opts_iv = _compute_options_iv_factor(latest_symbols, latest)
    scores["options_iv_skew_score"] = (
        scores["symbol"]
        .map(opts_iv.get("options_iv_skew_score", pd.Series(dtype=float)))
        .fillna(0.0)
        if "options_iv_skew_score" in opts_iv
        else 0.0
    )

    # Crash probability inverse -- not z-scored (scalar → zero variance).
    # Applied as multiplier post-composite via _crash_prediction_multiplier.

    # --- Cross-sectional z-score per factor (vectorized across all columns) ---
    # Use ddof=0 (population std) to avoid NaN for single-row universes.
    # For very small universes (< SMALL_UNIVERSE_THRESHOLD symbols), z-scoring
    # is statistically meaningless, so use rank-normalization instead.
    factor_cols = [c for c in scores.columns if c != "symbol"]
    n_rows = len(scores)
    # Item 48: fillna(0.0) BEFORE clip — missing factors treated as neutral (0).
    # This prevents NaN from propagating through rank/z-score into the composite.
    factor_df = scores[factor_cols].astype(float).fillna(0.0)
    if n_rows < SMALL_UNIVERSE_THRESHOLD:
        ranks = factor_df.rank(method="average", na_option="bottom")
        scores[factor_cols] = (((ranks / max(n_rows, 1)) - 0.5) * RANK_NORM_SCALE).clip(
            FACTOR_CLIP_MIN, FACTOR_CLIP_MAX
        )
    else:
        means = factor_df.mean()
        stds = factor_df.std(ddof=0)
        # Divide by std; set to NaN where std ≈ 0 (zero-variance factor), then
        # fill NaN → 0.0.  Avoid .where(valid, 0.0) with a column-indexed
        # boolean Series: pandas 2.x aligns it against the row index, not the
        # column axis, silently zeroing every cell.
        safe_stds = stds.replace(0.0, np.nan).where(
            stds > STD_ZERO_REPLACE, other=np.nan
        )
        normalized = (factor_df - means) / safe_stds
        # fillna(0.0): zero-variance factors and any residual NaN → neutral
        scores[factor_cols] = normalized.fillna(0.0).clip(
            FACTOR_CLIP_MIN, FACTOR_CLIP_MAX
        )

    # --- Weighted composite with regime-conditional weights ---
    # Fix 20: Only count factors that contributed non-zero values to avoid
    # dead factors diluting the composite via their weight in total_weight.
    # Item 47: Use safe_divide for the total_weight normalisation to guard
    # against the edge case where every factor is zero-variance.
    composite = pd.Series(0.0, index=scores.index)
    total_weight = 0.0
    used_factors = []
    for factor_name, weight in weights.items():
        if factor_name in scores.columns:
            factor_vals = scores[factor_name].fillna(0.0)
            if factor_vals.abs().sum() > FACTOR_ZERO_VARIANCE_EPS:
                composite += weight * factor_vals
                total_weight += weight
                used_factors.append(factor_name)

    # safe_divide: if no live factors (all zero-variance), composite stays 0.0
    composite = composite * safe_divide(1.0, total_weight, default=0.0)

    # --- Regime + crash exposure multiplier ---
    # crash_probability is applied ONLY via _crash_prediction_multiplier as a
    # risk-overlay exposure scaler (0.0–1.0). No separate additive/scaler
    # application — that would double-count.
    #
    regime_mult = REGIME_EXPOSURE.get(regime_label, 0.70)
    crash_mult = _crash_prediction_multiplier(df, cfg)
    exposure_mult = regime_mult * crash_mult

    # VIX hard cap — overrides regime/crash multiplier during vol spikes
    if "vix" in latest.columns:
        _vix_vals = latest["vix"].dropna()
        if len(_vix_vals) > 0:
            _vix_val = float(_vix_vals.median())
            # Tiered VIX cap: 4-tier coverage from moderate to extreme vol regimes
            # Thresholds from multifactor_v2_constants (calibrated vs stress tests)
            if _vix_val > VIX_THRESHOLD_EXTREME:
                _vix_cap = VIX_CAP_EXTREME  # extreme panic (GFC/COVID peak)
            elif _vix_val > VIX_THRESHOLD_CRISIS:
                _vix_cap = VIX_CAP_CRISIS  # crisis (GFC, COVID March)
            elif _vix_val > VIX_THRESHOLD_ELEVATED:
                _vix_cap = VIX_CAP_ELEVATED  # elevated stress (2022 inflation)
            elif _vix_val >= VIX_THRESHOLD_MILD:
                _vix_cap = VIX_CAP_MILD  # mild caution
            else:
                _vix_cap = 1.0
            if _vix_cap < exposure_mult:
                logger.info(
                    "[MF-V2] VIX=%.1f → exposure capped %.2f→%.2f",
                    _vix_val,
                    exposure_mult,
                    _vix_cap,
                )
                exposure_mult = _vix_cap

    # Yield-curve inversion cap — protects against slow stagflation bleeding
    # (VIX-cap alone misses low-VIX bear markets like 2022)
    if "yield_curve_slope" in latest.columns:
        _yc_vals = pd.to_numeric(latest["yield_curve_slope"], errors="coerce").dropna()
        if len(_yc_vals) > 0 and float(_yc_vals.median()) < 0:
            # Confirm persistence: require YIELD_CURVE_INVERSION_FRACTION of
            # last YIELD_CURVE_LOOKBACK_DAYS trading dates inverted
            _yc_persistent = False
            if "yield_curve_slope" in df.columns:
                _yc_hist = df.sort_values("timestamp").drop_duplicates(
                    "timestamp", keep="last"
                )
                _yc_recent = pd.to_numeric(
                    _yc_hist["yield_curve_slope"].tail(YIELD_CURVE_LOOKBACK_DAYS),
                    errors="coerce",
                ).dropna()
                if len(_yc_recent) >= YIELD_CURVE_INVERSION_MIN_HISTORY and (
                    _yc_recent < 0
                ).sum() >= min(20, len(_yc_recent) * YIELD_CURVE_INVERSION_FRACTION):
                    _yc_persistent = True
            else:
                _yc_persistent = (
                    False  # no panel history → cannot confirm persistence; skip cap
                )
            if _yc_persistent:
                _yc_cap = float(
                    cfg.get("yield_curve_inversion_cap", YIELD_CURVE_CAP_DEFAULT)
                )
                if _yc_cap < exposure_mult:
                    logger.info(
                        "[MF-V2] Yield-curve inverted (persistent) → exposure capped %.2f→%.2f",
                        exposure_mult,
                        _yc_cap,
                    )
                    exposure_mult = _yc_cap

    # Drawdown self-damper — halves exposure for 30 days after MDD > 12%
    with _DD_LOCK:
        if _DD_DAMPER["damper_active"]:
            _damp = float(_DD_DAMPER["damper_factor"])
            if _damp < 1.0:
                logger.info(
                    "[MF-V2] DD damper active → exposure scaled ×%.2f (until %s)",
                    _damp,
                    _DD_DAMPER["damper_until"],
                )
                exposure_mult = exposure_mult * _damp

    composite = composite * exposure_mult

    # --- Build output signals ---
    composite_arr = composite.to_numpy(dtype=float)
    ema_spread_arr = (
        scores["trend_ema_spread"].to_numpy(dtype=float)
        if "trend_ema_spread" in scores.columns
        else np.zeros(len(composite_arr))
    )
    sym_list = latest["symbol"].tolist()
    ts_list = (
        latest["timestamp"].tolist()
        if "timestamp" in latest.columns
        else [None] * len(latest)
    )
    scores_mat = scores[factor_cols].to_numpy(dtype=float)
    col_idx = {f: j for j, f in enumerate(factor_cols)}

    out = []
    for i in range(len(latest)):
        score = composite_arr[i]
        ema_spread = ema_spread_arr[i]
        if score > min_score and ema_spread > -0.5:
            row_scores = scores_mat[i]
            # Top contributing factors for reason string
            factor_contribs = [
                (f, float(row_scores[col_idx[f]]) * weights.get(f, 0.0))
                for f in used_factors
                if f in col_idx
            ]
            factor_contribs.sort(key=lambda x: abs(x[1]), reverse=True)
            reasons = [f"{f}={v:.2f}" for f, v in factor_contribs[:5]]

            out.append(
                {
                    "timestamp": ts_list[i],
                    "symbol": sym_list[i],
                    "direction": "LONG",
                    "score": float(score),
                    "reason": f"v2|regime={regime_label}|" + "; ".join(reasons),
                    # Preserve factor scores for meta-model
                    **{
                        f: float(row_scores[col_idx[f]])
                        for f in factor_cols
                        if f in col_idx
                    },
                }
            )

    if not out:
        return _empty_signals()

    result = pd.DataFrame(out).sort_values("score", ascending=False)

    # --- Meta-model confidence filter (opt-in) ---
    meta_cfg = cfg.get("meta_model") or {}
    if meta_cfg.get("enabled", False):
        try:
            result = _apply_meta_model_filter(result, meta_cfg)
        except Exception as exc:
            logger.debug("[MF-V2] meta_model filter skipped: %s", exc)

    logger.info(
        "[MF-V2] %d LONG signals from %d symbols "
        "(regime=%s, exposure=%.2f, crash_mult=%.3f, active_factors=%d/%d)",
        len(result),
        len(latest),
        regime_label,
        exposure_mult,
        crash_mult,
        len(used_factors),
        len(weights),
    )
    return result


def _apply_meta_model_filter(
    signals: pd.DataFrame,
    meta_cfg: dict[str, Any],
) -> pd.DataFrame:
    """Load classifier, compute confidence, filter / scale signals."""
    model_path = meta_cfg.get("model_path")
    if not model_path or not Path(model_path).exists():
        raise FileNotFoundError(f"meta_model path missing: {model_path}")

    min_conf = float(meta_cfg.get("min_confidence", 0.55))

    import joblib

    try:
        model = joblib.load(model_path)
    except (EOFError, Exception) as exc:
        raise RuntimeError(
            f"[multifactor_v2] Failed to load meta-model from {model_path}: {exc}"
        ) from exc

    feature_cols = meta_cfg.get("feature_cols")
    if not feature_cols:
        feature_cols = [
            c
            for c in signals.columns
            if c.startswith(
                (
                    "trend_",
                    "mom_",
                    "mr_",
                    "vol_",
                    "vola_",
                    "breadth_",
                    "sector_",
                    "earnings_",
                    "insider_",
                    "news_",
                    "macro_",
                    "intermarket_",
                    "options_",
                    "vix_",
                    "crash_",
                )
            )
        ]
    if not feature_cols:
        raise ValueError("meta_model: no feature columns available")

    missing = [c for c in feature_cols if c not in signals.columns]
    if missing:
        raise ValueError(f"meta_model: missing columns: {missing}")

    # Guard against silent feature poisoning: fillna(0.0) treats a data-feed
    # gap as a real standardized value, drifting confidence without warning.
    # Predict only on rows with complete features; rows with any NaN feature
    # get meta_confidence=NaN and are filtered by the min_conf gate below.
    feat_frame = signals[feature_cols]
    complete_mask = feat_frame.notna().all(axis=1).to_numpy()
    n_nan_rows = int((~complete_mask).sum())
    if n_nan_rows > 0:
        logger.warning(
            "[multifactor_v2.meta_model] %d/%d rows skipped due to NaN features",
            n_nan_rows,
            len(signals),
        )

    confidence = np.full(len(signals), np.nan, dtype=float)
    if complete_mask.any():
        X = feat_frame.loc[complete_mask].to_numpy()
        proba = model.predict_proba(X)
        if proba.ndim != 2 or proba.shape[1] < 2:
            raise ValueError(f"meta_model: unexpected shape {proba.shape}")
        confidence[complete_mask] = proba[:, 1]

    out = signals.copy()
    out["meta_confidence"] = confidence
    out = out.loc[np.nan_to_num(confidence, nan=-1.0) >= min_conf].copy()
    if out.empty:
        return out
    if "score" in out.columns:
        out["score"] = out["score"].astype(float) * out["meta_confidence"].astype(float)
    return out.reset_index(drop=True)


# ---------------------------------------------------------------------------
# Target positions — delegates to v1 (sizing is orthogonal to signal gen)
# ---------------------------------------------------------------------------


def compute_target_positions(*args: Any, **kwargs: Any) -> pd.DataFrame:
    """v2 target positions — delegates to v1.

    Sizing logic (score-proportional, HRP, BL) is configured via
    strategy_cfg["sizing_method"] and handled by v1's implementation.
    """
    return _v1_compute_target_positions(*args, **kwargs)


# ---------------------------------------------------------------------------
# ATR-regime adaptive exits
# ---------------------------------------------------------------------------

# ATR multipliers per regime
_STOP_ATR_MULT = {"bull": 3.0, "sideways": 2.0, "bear": 1.5, "crisis": 1.0}
_TRAIL_ATR_MULT = {"bull": 2.5, "sideways": 1.8, "bear": 1.2, "crisis": 0.8}
_TP_ATR_MULT = {"bull": 4.0, "sideways": 3.0, "bear": 2.0, "crisis": 1.5}


def _compute_atr(df: pd.DataFrame, symbol: str, window: int = 14) -> float:
    """Compute Average True Range for a symbol."""
    # Callers may pass frames without a timestamp column (e.g. already
    # latest-per-symbol snapshots). Skip the sort when timestamp is absent
    # so the function never raises KeyError on legitimate inputs.
    if "symbol" in df.columns:
        sym_df = df[df["symbol"] == symbol]
    else:
        sym_df = df
    if "timestamp" in sym_df.columns:
        sym_df = sym_df.sort_values("timestamp")
    if len(sym_df) < window + 1:
        return 0.0

    high = pd.to_numeric(
        sym_df.get("high", sym_df.get("close", pd.Series(dtype=float))), errors="coerce"
    )
    low = pd.to_numeric(
        sym_df.get("low", sym_df.get("close", pd.Series(dtype=float))), errors="coerce"
    )
    close = pd.to_numeric(sym_df.get("close", pd.Series(dtype=float)), errors="coerce")

    prev_close = close.shift(1)
    tr = pd.concat(
        [
            (high - low).abs(),
            (high - prev_close).abs(),
            (low - prev_close).abs(),
        ],
        axis=1,
    ).max(axis=1)

    atr = tr.iloc[-window:].mean()
    return float(atr) if np.isfinite(atr) else 0.0


def check_exit_signals(
    current_positions: dict,
    prices_latest: pd.DataFrame,
    strategy_cfg: dict | None = None,
) -> pd.DataFrame:
    """ATR-regime adaptive exit signals.

    Uses regime-dependent ATR multipliers for stop-loss, trailing-stop,
    and take-profit. Includes momentum verification to reduce whipsaws.
    Falls back to v1 static exits if ATR computation fails.
    """
    cfg = strategy_cfg or {}
    exit_cfg = cfg.get("exits", {})
    exit_mode = exit_cfg.get("mode", "atr_regime")

    empty = pd.DataFrame(columns=["symbol", "direction", "exit_reason", "exit_qty_pct"])

    if not current_positions or prices_latest is None or prices_latest.empty:
        return empty

    # Fall back to static exits if configured
    if exit_mode == "static":
        from src.assembled_core.strategies.multifactor_v1 import (
            check_exit_signals as _v1_exits,
        )

        return _v1_exits(current_positions, prices_latest, strategy_cfg)

    # Detect regime for ATR multipliers
    regime = (
        _detect_regime(prices_latest, cfg)
        if "symbol" in prices_latest.columns
        else "sideways"
    )

    stop_mult = _STOP_ATR_MULT.get(regime, 2.0)
    trail_mult = _TRAIL_ATR_MULT.get(regime, 1.8)
    tp_mult = _TP_ATR_MULT.get(regime, 3.0)

    # Override from config if provided
    if "stop_atr_mult_by_regime" in exit_cfg:
        stop_mult = exit_cfg["stop_atr_mult_by_regime"].get(regime, stop_mult)
    if "trail_atr_mult_by_regime" in exit_cfg:
        trail_mult = exit_cfg["trail_atr_mult_by_regime"].get(regime, trail_mult)
    if "tp_atr_mult_by_regime" in exit_cfg:
        tp_mult = exit_cfg["tp_atr_mult_by_regime"].get(regime, tp_mult)

    atr_window = int(exit_cfg.get("atr_window") or 14)
    momentum_verify = exit_cfg.get("momentum_verification", True)
    time_stop_days = int(exit_cfg.get("time_stop_days") or 30)
    time_stop_min_return = float(exit_cfg.get("time_stop_min_return", 0.03))

    price_map = {}
    if "symbol" in prices_latest.columns and "close" in prices_latest.columns:
        price_map = dict(
            zip(prices_latest["symbol"].values, prices_latest["close"].values)
        )

    exits = []
    for sym, pos in current_positions.items():
        qty = float(pos.get("qty", 0))
        if qty <= 0:
            continue
        avg_price = float(pos.get("avg_price", 0))
        hwm = float(pos.get("hwm", avg_price))
        if avg_price <= 0:
            continue

        current_price = float(price_map.get(sym, 0))
        if current_price <= 0:
            continue

        if current_price > hwm:
            hwm = current_price

        atr = _compute_atr(prices_latest, sym, atr_window)
        if atr <= 0:
            # Fallback to percentage-based stops
            atr = avg_price * 0.02  # ~2% as proxy

        # --- Stop-loss (ATR-based) ---
        stop_price = avg_price - stop_mult * atr
        if current_price <= stop_price:
            # Momentum verification: skip exit if RSI < 30 and EMA trending up
            if momentum_verify and _momentum_intact(prices_latest, sym):
                logger.debug("[MF-V2] %s: stop hit but momentum intact, holding", sym)
                continue
            exits.append(
                {
                    "symbol": sym,
                    "direction": "FLAT",
                    "exit_reason": f"stop_atr_{regime} ({current_price:.2f} <= {stop_price:.2f})",
                    "exit_qty_pct": 1.0,
                }
            )
            continue

        # --- Trailing stop (ATR-based on HWM) ---
        if hwm > avg_price:
            trail_price = hwm - trail_mult * atr
            if current_price <= trail_price:
                exits.append(
                    {
                        "symbol": sym,
                        "direction": "FLAT",
                        "exit_reason": f"trailing_atr_{regime} ({current_price:.2f} <= {trail_price:.2f}, hwm={hwm:.2f})",
                        "exit_qty_pct": 1.0,
                    }
                )
                continue

        # --- Take-profit (partial, ATR-based) ---
        tp_price = avg_price + tp_mult * atr
        if current_price >= tp_price:
            exits.append(
                {
                    "symbol": sym,
                    "direction": "FLAT",
                    "exit_reason": f"take_profit_atr_{regime} ({current_price:.2f} >= {tp_price:.2f})",
                    "exit_qty_pct": 0.5,
                }
            )
            continue

        # --- Time stop (zombie killer) ---
        days_held = int(pos.get("days_held", 0))
        if days_held > time_stop_days:
            return_pct = (
                (current_price - avg_price) / avg_price if avg_price > 0 else 0.0
            )
            if return_pct < time_stop_min_return:
                exits.append(
                    {
                        "symbol": sym,
                        "direction": "FLAT",
                        "exit_reason": f"time_stop ({days_held}d, return={return_pct:.2%} < {time_stop_min_return:.2%})",
                        "exit_qty_pct": 1.0,
                    }
                )
                continue

    if not exits:
        return empty
    return pd.DataFrame(exits)


def _momentum_intact(prices_latest: pd.DataFrame, symbol: str) -> bool:
    """Check if momentum is still intact (whipsaw protection).

    Returns True if RSI < 30 AND short-term EMA is above long-term EMA,
    suggesting the stop hit is a dip-in-uptrend rather than a reversal.
    """
    try:
        if "symbol" not in prices_latest.columns:
            return False
        sym_df = prices_latest[prices_latest["symbol"] == symbol]
        if sym_df.empty:
            return False

        row = sym_df.iloc[-1]
        rsi = float(row.get("ta_rsi_14_v1", 50.0))
        if rsi >= 30:
            return False

        # Check EMA trend
        ema_spread = float(row.get("trend_ema_spread", 0.0))
        if ema_spread <= 0:
            return False

        return True
    except Exception as _exc:
        logger.debug("[MF-V2] _momentum_intact failed: %s", _exc)
        return False


__all__ = [
    "compute_signals",
    "compute_target_positions",
    "check_exit_signals",
    "clear_regime_cache",
    "reset_dd_damper",
    "update_drawdown_damper",
]
