"""Appends batch 21 (final) tests to the session test file."""

from pathlib import Path

lines = [
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# BATCH 21 (FINAL): BACKLOG_ERGAENZUNG items 122, 131, 135, 146/147, 166/167",
    "#  + BACKLOG_NACH_PILOT supplemental checks",
    "# ---------------------------------------------------------------------------",
    "",
    "",
    "class TestPhantomModuleImportGuards:",
    "    '''Item 122: Optional/phantom modules use try/except ImportError gracefully.'''",
    "",
    "    def test_optional_import_pattern_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        optional_import_count = 0",
    "        for f in src.rglob('*.py'):",
    "            if '__pycache__' in str(f):",
    "                continue",
    "            try:",
    "                content = f.read_text(encoding='utf-8', errors='replace')",
    "                if 'ImportError' in content and 'try' in content:",
    "                    optional_import_count += 1",
    "            except OSError:",
    "                pass",
    "        assert optional_import_count >= 10, (",
    "            f'Too few optional import guards: {optional_import_count} — canary modules need ImportError handling'",
    "        )",
    "",
    "    def test_canary_modules_have_import_guard(self):",
    "        src = Path(__file__).parents[1] / 'src' / 'assembled_core'",
    "        # Canary modules are those with heavy optional deps like torch, quantlib, etc.",
    "        canary_files = list(src.rglob('*rl_environment*')) + list(src.rglob('*kalshi*')) + list(src.rglob('*polymarket*'))",
    "        canary_files = [f for f in canary_files if '__pycache__' not in str(f) and f.suffix == '.py']",
    "        for f in canary_files:",
    "            content = f.read_text(encoding='utf-8', errors='replace')",
    "            # Canary modules should have graceful import handling",
    "            has_guard = 'ImportError' in content or 'ModuleNotFoundError' in content or 'TYPE_CHECKING' in content",
    "            assert has_guard, f'{f.name} should have ImportError guard for optional dependencies'",
    "",
    "",
    "class TestPilotLearningsDocs:",
    "    '''Item 131: Pilot v1 crash logs and learnings are documented.'''",
    "",
    "    def test_known_issues_mentions_pilot(self):",
    "        root = Path(__file__).parents[1]",
    "        ki = root / 'KNOWN_ISSUES.md'",
    "        if not ki.exists():",
    "            return",
    "        content = ki.read_text(encoding='utf-8', errors='replace')",
    "        has_pilot = 'pilot' in content.lower() or 'paper' in content.lower()",
    "        assert has_pilot, 'KNOWN_ISSUES.md should reference pilot/paper trading learnings'",
    "",
    "    def test_operating_or_runbook_exists(self):",
    "        root = Path(__file__).parents[1]",
    "        docs = root / 'docs'",
    "        ops_docs = []",
    "        if docs.exists():",
    "            ops_docs = list(docs.rglob('*OPERATING*')) + list(docs.rglob('*operating*'))",
    "            ops_docs += list(docs.rglob('*runbook*')) + list(docs.rglob('*RUNBOOK*'))",
    "        ops_docs += list(root.glob('OPERATING*.md'))",
    "        assert len(ops_docs) >= 1, 'An OPERATING or runbook document should exist'",
    "",
    "",
    "class TestSingleMachineArchitecture:",
    "    '''Item 135: Single-machine architecture constraints are explicit.'''",
    "",
    "    def test_concurrent_write_protection_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        lock_count = 0",
    "        for f in src.rglob('*.py'):",
    "            if '__pycache__' in str(f):",
    "                continue",
    "            try:",
    "                content = f.read_text(encoding='utf-8', errors='replace')",
    "                if any(kw in content for kw in ['threading.Lock', 'FileLock', 'filelock', 'portalocker']):",
    "                    lock_count += 1",
    "            except OSError:",
    "                pass",
    "        assert lock_count >= 3, f'Too few concurrent-write protections: {lock_count}'",
    "",
    "    def test_no_multiprocessing_spawn_in_core(self):",
    "        # Core pipeline should not spawn subprocesses (single-machine simplicity)",
    "        src = Path(__file__).parents[1] / 'src' / 'assembled_core' / 'pipeline'",
    "        if not src.exists():",
    "            return",
    "        spawn_count = 0",
    "        for f in src.rglob('*.py'):",
    "            if '__pycache__' in str(f):",
    "                continue",
    "            try:",
    "                content = f.read_text(encoding='utf-8', errors='replace')",
    "                if 'subprocess.run' in content or 'multiprocessing.Process' in content:",
    "                    spawn_count += 1",
    "            except OSError:",
    "                pass",
    "        assert spawn_count == 0, f'Pipeline core should not spawn subprocesses: {spawn_count}'",
    "",
    "",
    "class TestDailyReviewInfrastructure:",
    "    '''Item 147: Daily review infrastructure exists (QA reports).'''",
    "",
    "    def test_daily_qa_report_script_exists(self):",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        qa_scripts = (",
    "            list(scripts.rglob('*daily_qa*')) +",
    "            list(scripts.rglob('*generate_daily*')) +",
    "            list(scripts.rglob('*daily_report*'))",
    "        )",
    "        qa_scripts = [f for f in qa_scripts if '__pycache__' not in str(f)]",
    "        assert len(qa_scripts) >= 1, 'A daily QA report script should exist'",
    "",
    "    def test_paper_summary_module_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        summary = list(src.rglob('paper_summary.py')) + list(src.rglob('ops/paper_summary.py'))",
    "        summary = [f for f in summary if '__pycache__' not in str(f)]",
    "        assert len(summary) >= 1, 'paper_summary.py should exist for daily review'",
    "",
    "",
    "class TestBrokerageAPIAbstraction:",
    "    '''Item 166/125: Broker abstraction allows switching between paper/live brokers.'''",
    "",
    "    def test_order_router_has_broker_abstraction(self):",
    "        src = Path(__file__).parents[1] / 'src' / 'assembled_core'",
    "        router = src / 'execution' / 'order_router.py'",
    "        if not router.exists():",
    "            return",
    "        content = router.read_text(encoding='utf-8', errors='replace')",
    "        # Should have some form of broker abstraction (paper vs live)",
    "        has_abstraction = any(kw in content for kw in ['paper', 'live', 'broker', 'Paper', 'Live', 'Broker'])",
    "        assert has_abstraction, 'order_router should have broker abstraction'",
    "",
    "    def test_paper_mode_config_exists(self):",
    "        policy = Path(__file__).parents[1] / 'configs' / 'policy.yaml'",
    "        if not policy.exists():",
    "            return",
    "        content = policy.read_text(encoding='utf-8', errors='replace')",
    "        has_paper = 'paper' in content.lower() or 'trading_mode' in content",
    "        assert has_paper, 'policy.yaml should reference paper trading mode'",
    "",
    "",
    "class TestTaxAwareTrading:",
    "    '''Item 167: Tax-aware trading considerations are in place.'''",
    "",
    "    def test_wash_sale_guard_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        ws = list(src.rglob('*wash_sale*.py'))",
    "        ws = [f for f in ws if '__pycache__' not in str(f)]",
    "        assert len(ws) >= 1, 'wash_sale guard should exist for tax-aware trading'",
    "",
    "    def test_accounting_module_has_pnl_tracking(self):",
    "        src = Path(__file__).parents[1] / 'src' / 'assembled_core' / 'accounting'",
    "        if not src.exists():",
    "            return",
    "        pnl_files = list(src.rglob('*.py'))",
    "        pnl_files = [f for f in pnl_files if '__pycache__' not in str(f)]",
    "        combined = ' '.join(f.read_text(encoding='utf-8', errors='replace') for f in pnl_files)",
    "        has_pnl = 'realized_pnl' in combined or 'unrealized' in combined or 'pnl' in combined.lower()",
    "        assert has_pnl, 'Accounting module should track P&L for tax purposes'",
    "",
    "",
    "class TestSupplementalInfraChecks:",
    "    '''Supplemental: Additional infrastructure completeness checks.'''",
    "",
    "    def test_env_validator_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        found = False",
    "        for directory in [src, scripts]:",
    "            for f in directory.rglob('*.py'):",
    "                if '__pycache__' in str(f):",
    "                    continue",
    "                if 'env_valid' in f.name.lower() or 'validate_env' in f.name.lower():",
    "                    found = True",
    "                    break",
    "        assert found, 'An env_validator or validate_env module should exist'",
    "",
    "    def test_position_sync_module_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        ps = list(src.rglob('position_sync.py'))",
    "        ps = [f for f in ps if '__pycache__' not in str(f)]",
    "        assert len(ps) >= 1, 'position_sync.py should exist for state reconciliation'",
    "",
    "    def test_regime_detection_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        regime = list(src.rglob('*regime*.py'))",
    "        regime = [f for f in regime if '__pycache__' not in str(f)]",
    "        assert len(regime) >= 2, f'Regime detection modules should exist: {[f.name for f in regime]}'",
    "",
    "    def test_factor_store_has_factor_methods(self):",
    "        p = Path(__file__).parents[1] / 'src' / 'assembled_core' / 'data' / 'feature_store.py'",
    "        if not p.exists():",
    "            return",
    "        content = p.read_text(encoding='utf-8', errors='replace')",
    "        has_methods = 'def get' in content or 'def store' in content or 'def load' in content",
    "        assert has_methods, 'feature_store.py should have get/store/load methods'",
    "",
    "    def test_hrp_is_importable(self):",
    "        p = Path(__file__).parents[1] / 'src' / 'assembled_core' / 'portfolio' / 'hierarchical_risk_parity.py'",
    "        assert p.exists(), 'hierarchical_risk_parity.py should exist'",
    "        content = p.read_text(encoding='utf-8', errors='replace')",
    "        assert 'def ' in content, 'HRP module should have functions'",
]

target = Path("tests/test_session_2026_05_07_new_items.py")
with open(target, "a", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
print("Batch 21 appended successfully.")
