"""Appends batch 20 tests to the session test file."""

from pathlib import Path

lines = [
    "",
    "",
    "# ---------------------------------------------------------------------------",
    "# BATCH 20: BACKLOG_ERGAENZUNG items 160, 161, 162, 163, 164, 165, 166, 167,",
    "#            168, 169, 170, 171, 172",
    "# ---------------------------------------------------------------------------",
    "",
    "",
    "class TestWebCrawlerSecurity:",
    "    '''Item 160: Cookie/web-crawler usage is secure (no credential leakage).'''",
    "",
    "    def test_no_hardcoded_cookies(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        import re",
    "        cookie_pattern = re.compile(r'cookie\\s*=\\s*[\"\\'][^\"\\'\\.\\$]+[\"\\']', re.IGNORECASE)",
    "        violations = []",
    "        for directory in [src, scripts]:",
    "            for f in directory.rglob('*.py'):",
    "                if '__pycache__' in str(f):",
    "                    continue",
    "                try:",
    "                    content = f.read_text(encoding='utf-8', errors='replace')",
    "                    if cookie_pattern.search(content) and 'test_' not in f.name:",
    "                        violations.append(f.name)",
    "                except OSError:",
    "                    pass",
    "        assert len(violations) <= 3, f'Possible hardcoded cookies: {violations}'",
    "",
    "    def test_requests_session_used_safely(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        timeout_count = 0",
    "        requests_count = 0",
    "        for directory in [src, scripts]:",
    "            for f in directory.rglob('*.py'):",
    "                if '__pycache__' in str(f):",
    "                    continue",
    "                try:",
    "                    content = f.read_text(encoding='utf-8', errors='replace')",
    "                    if 'requests.' in content or 'requests.get' in content:",
    "                        requests_count += 1",
    "                        if 'timeout=' in content:",
    "                            timeout_count += 1",
    "                except OSError:",
    "                    pass",
    "        if requests_count > 0:",
    "            ratio = timeout_count / requests_count",
    "            assert ratio >= 0.5, f'Too few requests calls have timeout: {timeout_count}/{requests_count}'",
    "",
    "",
    "class TestTestResourceCleanup:",
    "    '''Item 161: Test resources are cleaned up properly.'''",
    "",
    "    def test_tmp_path_or_teardown_used(self):",
    "        tests = Path(__file__).parents[1] / 'tests'",
    "        cleanup_count = 0",
    "        for f in tests.rglob('*.py'):",
    "            if '__pycache__' in str(f):",
    "                continue",
    "            try:",
    "                content = f.read_text(encoding='utf-8', errors='replace')",
    "                if 'tmp_path' in content or 'teardown' in content.lower() or 'autouse' in content:",
    "                    cleanup_count += 1",
    "            except OSError:",
    "                pass",
    "        assert cleanup_count >= 1, 'At least one test file should use tmp_path or teardown'",
    "",
    "    def test_no_leftover_test_files(self):",
    "        root = Path(__file__).parents[1]",
    "        # Check for temp test output files that shouldn't be committed",
    "        suspicious = list(root.glob('test_output_*.parquet')) + list(root.glob('test_*.csv'))",
    "        suspicious = [f for f in suspicious if f.is_file()]",
    "        assert len(suspicious) == 0, f'Leftover test output files: {[f.name for f in suspicious]}'",
    "",
    "",
    "class TestLoggingRotation:",
    "    '''Item 162: Logging rotation and disk-space management exists.'''",
    "",
    "    def test_rotating_file_handler_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        found = False",
    "        for directory in [src, scripts]:",
    "            for f in directory.rglob('*.py'):",
    "                if '__pycache__' in str(f):",
    "                    continue",
    "                try:",
    "                    content = f.read_text(encoding='utf-8', errors='replace')",
    "                    if 'RotatingFileHandler' in content or 'TimedRotatingFileHandler' in content:",
    "                        found = True",
    "                        break",
    "                except OSError:",
    "                    pass",
    "        assert found, 'RotatingFileHandler or TimedRotatingFileHandler should exist'",
    "",
    "    def test_log_level_configurable(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        configurable = False",
    "        for directory in [src, scripts]:",
    "            for f in directory.rglob('*.py'):",
    "                if '__pycache__' in str(f):",
    "                    continue",
    "                try:",
    "                    content = f.read_text(encoding='utf-8', errors='replace')",
    "                    if ('LOG_LEVEL' in content or 'log_level' in content) and (",
    "                        'os.environ' in content or 'os.getenv' in content",
    "                    ):",
    "                        configurable = True",
    "                        break",
    "                except OSError:",
    "                    pass",
    "        assert configurable, 'LOG_LEVEL should be configurable via env var'",
    "",
    "",
    "class TestDisasterRecovery:",
    "    '''Item 163: Disaster recovery runbook and alerting failover exist.'''",
    "",
    "    def test_disaster_runbook_exists(self):",
    "        root = Path(__file__).parents[1]",
    "        docs_dir = root / 'docs'",
    "        runbooks = []",
    "        if docs_dir.exists():",
    "            runbooks = list(docs_dir.rglob('*disaster*')) + list(docs_dir.rglob('*runbook*'))",
    "        if not runbooks:",
    "            # Also check root level",
    "            runbooks = list(root.glob('*DISASTER*')) + list(root.glob('*RUNBOOK*'))",
    "        assert len(runbooks) >= 1, 'A disaster recovery runbook should exist'",
    "",
    "    def test_alerting_config_exists(self):",
    "        root = Path(__file__).parents[1]",
    "        configs = root / 'configs'",
    "        alerting = list(configs.glob('*alert*')) if configs.exists() else []",
    "        if not alerting:",
    "            alerting = list(root.rglob('alerting.yaml')) + list(root.rglob('*alert*.yaml'))",
    "        alerting = [f for f in alerting if '__pycache__' not in str(f)]",
    "        assert len(alerting) >= 1, 'An alerting config (alerting.yaml) should exist'",
    "",
    "    def test_kill_switch_module_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        ks = list(src.rglob('kill_switch.py'))",
    "        ks = [f for f in ks if '__pycache__' not in str(f)]",
    "        assert len(ks) >= 1, 'kill_switch.py should exist for disaster recovery'",
    "",
    "",
    "class TestNetworkTimeouts:",
    "    '''Item 164: Network timeout strategies for all external API calls.'''",
    "",
    "    def test_external_api_calls_have_timeouts(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        scripts = Path(__file__).parents[1] / 'scripts'",
    "        timeout_files = []",
    "        for directory in [src, scripts]:",
    "            for f in directory.rglob('*.py'):",
    "                if '__pycache__' in str(f):",
    "                    continue",
    "                try:",
    "                    content = f.read_text(encoding='utf-8', errors='replace')",
    "                    if 'timeout=' in content and any(",
    "                        kw in content for kw in ['requests', 'yfinance', 'http', 'urllib', 'aiohttp']",
    "                    ):",
    "                        timeout_files.append(f.name)",
    "                except OSError:",
    "                    pass",
    "        assert len(timeout_files) >= 3, f'Too few files with timeouts: {timeout_files}'",
    "",
    "    def test_default_timeout_constant_exists(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        has_default = False",
    "        for f in src.rglob('*.py'):",
    "            if '__pycache__' in str(f):",
    "                continue",
    "            try:",
    "                content = f.read_text(encoding='utf-8', errors='replace')",
    "                if 'DEFAULT_TIMEOUT' in content or 'REQUEST_TIMEOUT' in content or 'HTTP_TIMEOUT' in content:",
    "                    has_default = True",
    "                    break",
    "            except OSError:",
    "                pass",
    "        assert has_default, 'A DEFAULT_TIMEOUT constant should exist'",
    "",
    "",
    "class TestEDGARThrottling:",
    "    '''Item 165: SEC EDGAR throttling is implemented.'''",
    "",
    "    def test_edgar_source_has_rate_limiting(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        edgar_files = list(src.rglob('edgar_source.py')) + list(src.rglob('*edgar*.py'))",
    "        edgar_files = [f for f in edgar_files if '__pycache__' not in str(f)]",
    "        if not edgar_files:",
    "            return",
    "        content = edgar_files[0].read_text(encoding='utf-8', errors='replace')",
    "        has_throttle = any(kw in content for kw in ['RateLimiter', 'rate_limit', 'sleep', 'throttle', 'EDGAR_THROTTLE'])",
    "        assert has_throttle, 'edgar_source.py should have rate limiting (10 req/sec max)'",
    "",
    "    def test_edgar_user_agent_set(self):",
    "        src = Path(__file__).parents[1] / 'src'",
    "        edgar_files = list(src.rglob('edgar_source.py')) + list(src.rglob('*edgar*.py'))",
    "        edgar_files = [f for f in edgar_files if '__pycache__' not in str(f)]",
    "        if not edgar_files:",
    "            return",
    "        content = edgar_files[0].read_text(encoding='utf-8', errors='replace')",
    "        has_ua = 'User-Agent' in content or 'user_agent' in content.lower() or 'headers' in content",
    "        assert has_ua, 'EDGAR requests should set User-Agent header (SEC requirement)'",
    "",
    "",
    "class TestBacklogDocumentation:",
    "    '''Items 169/170/171/172: Backlog has ToC, cross-refs, and effort estimates.'''",
    "",
    "    def test_backlog_files_exist(self):",
    "        root = Path(__file__).parents[1]",
    "        backlog_dir = root / 'autonome_weiterarbeit'",
    "        if not backlog_dir.exists():",
    "            return",
    "        backlogs = list(backlog_dir.glob('BACKLOG*.md'))",
    "        assert len(backlogs) >= 2, 'Multiple backlog files should exist'",
    "",
    "    def test_backlog_has_priority_markers(self):",
    "        root = Path(__file__).parents[1]",
    "        backlog_dir = root / 'autonome_weiterarbeit'",
    "        if not backlog_dir.exists():",
    "            return",
    "        found_priority = False",
    "        for f in backlog_dir.glob('BACKLOG*.md'):",
    "            content = f.read_text(encoding='utf-8', errors='replace')",
    "            if any(kw in content for kw in ['WICHTIG', 'BLOCKER', 'VOR_LIVE', 'BACKLOG']):",
    "                found_priority = True",
    "                break",
    "        assert found_priority, 'Backlog should have priority markers like [WICHTIG], [BLOCKER]'",
    "",
    "    def test_backlog_ergaenzung_has_sections(self):",
    "        root = Path(__file__).parents[1]",
    "        backlog_dir = root / 'autonome_weiterarbeit'",
    "        if not backlog_dir.exists():",
    "            return",
    "        ergaenzung = backlog_dir / 'BACKLOG_ERGAENZUNG.md'",
    "        if not ergaenzung.exists():",
    "            return",
    "        content = ergaenzung.read_text(encoding='utf-8', errors='replace')",
    "        section_count = content.count('# ABSCHNITT')",
    "        assert section_count >= 5, f'BACKLOG_ERGAENZUNG.md should have sections: {section_count}'",
    "",
    "",
    "class TestPilotSuccessDefinition:",
    "    '''Item 148: Pilot success criteria are defined somewhere.'''",
    "",
    "    def test_pilot_success_defined(self):",
    "        root = Path(__file__).parents[1]",
    "        docs_dir = root / 'docs'",
    "        policy = root / 'configs' / 'policy.yaml'",
    "        has_success_def = False",
    "        # Check policy.yaml or any doc for success criteria",
    "        if policy.exists():",
    "            content = policy.read_text(encoding='utf-8', errors='replace')",
    "            if 'target' in content and any(kw in content for kw in ['sharpe', 'cagr', 'drawdown', 'mdd']):",
    "                has_success_def = True",
    "        if not has_success_def and docs_dir.exists():",
    "            for doc in docs_dir.rglob('*.md'):",
    "                try:",
    "                    content = doc.read_text(encoding='utf-8', errors='replace')",
    "                    if 'success' in content.lower() and 'pilot' in content.lower():",
    "                        has_success_def = True",
    "                        break",
    "                except OSError:",
    "                    pass",
    "        assert has_success_def, 'Pilot success criteria should be defined in policy or docs'",
    "",
    "",
    "class TestDrawdownPsychologicalPrep:",
    "    '''Item 168: Drawdown psychological preparation is documented.'''",
    "",
    "    def test_drawdown_limit_in_policy(self):",
    "        policy = Path(__file__).parents[1] / 'configs' / 'policy.yaml'",
    "        if not policy.exists():",
    "            return",
    "        content = policy.read_text(encoding='utf-8', errors='replace')",
    "        has_dd = any(kw in content for kw in ['max_drawdown', 'drawdown_limit', 'mdd', 'drawdown'])",
    "        assert has_dd, 'policy.yaml should define drawdown limits'",
    "",
    "    def test_known_issues_mentions_risk_limits(self):",
    "        root = Path(__file__).parents[1]",
    "        ki = root / 'KNOWN_ISSUES.md'",
    "        if not ki.exists():",
    "            return",
    "        content = ki.read_text(encoding='utf-8', errors='replace')",
    "        has_risk = any(kw in content.lower() for kw in ['drawdown', 'stress', 'risk', 'mdd', 'loss'])",
    "        assert has_risk, 'KNOWN_ISSUES.md should mention risk/drawdown context'",
]

target = Path("tests/test_session_2026_05_07_new_items.py")
with open(target, "a", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
print("Batch 20 appended successfully.")
